repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        language: system
        entry: npm run lint:oxlint
        stages: [pre-commit]
        pass_filenames: false

      - id: type-check
        name: Type Check
        language: system
        entry: npm run type-check
        stages: [pre-commit]
        pass_filenames: false

      - id: test
        name: Test
        language: system
        entry: npm run type-check
        stages: [pre-commit]
        pass_filenames: false

      - id: format
        name: Format
        language: system
        entry: npm run format
        stages: [pre-commit]
        pass_filenames: false
