# Prettier configuration file
# https://prettier.io/docs/en/configuration.html

$schema: 'https://json.schemastore.org/prettierrc'
semi: false
tabWidth: 2
useTabs: true
printWidth: 100
singleQuote: true
vueIndentScriptAndStyle: true
plugins:
  - prettier-plugin-organize-imports
  - '@prettier/plugin-oxc'
