repos:
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        entry: pnpm format
        stages: [pre-push]
        pass_filenames: false

      - id: type-check
        name: Type Check
        language: system
        entry: pnpm type-check
        stages: [pre-push]
        pass_filenames: false
