$schema: https://json.schemastore.org/prettierrc
semi: true
tabWidth: 2
useTabs: true
printWidth: 100
singleQuote: true
vueIndentScriptAndStyle: true

plugins:
  - prettier-plugin-organize-imports
  - '@prettier/plugin-oxc'
  - prettier-plugin-tailwindcss
  - prettier-plugin-svelte

overrides:
  - files: "*.svelte"
    options:
      parser: svelte