import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoAccordionValue = string | number | (string | number)[];

export interface BoAccordionProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/** The active item value(s) (v-model). */
	modelValue?: BoAccordionValue;
	/** The default open item value(s) when uncontrolled. */
	defaultValue?: BoAccordionValue;
	/** Whether multiple items can be open at once. */
	multiple?: boolean;
	/** Whether items are collapsible (can all be closed). */
	collapsible?: boolean;
	/** Whether the accordion is disabled. */
	disabled?: boolean;
}

type BoAccordionManifestDefaults = Pick<BoAccordionProps, 'multiple' | 'collapsible'>;

export interface BoAccordionStyleManifest {
	base: string;
	item: string;
	header: string;
	trigger: string;
	icon: string;
	content: string;
	contentInner: string;
	contentBody: string;
}

export type AccordionManifest = ComponentManifest<
	BoAccordionStyleManifest,
	BoAccordionManifestDefaults
>;

export interface BoAccordionItemProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/** The value of the item. */
	value: string | number;
	/** Whether the item is disabled. */
	disabled?: boolean;
	/** The role of the content region. */
	role?: HTMLAttributes['role'];
}
