import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoAlertSize = 'sm' | 'default' | 'lg';

export type BoAlertVariant = 'info' | 'success' | 'warning' | 'error';

export interface BoAlertProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: string;
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the alert.
	 * @default 'default'
	 */
	size?: BoAlertSize;
	/**
	 * The variant of the alert. This determines
	 * the color properties of the alert.
	 *
	 * @default 'info'
	 */
	variant?: BoAlertVariant;
	/**
	 * The title of the alert.
	 */
	title?: string;
	/**
	 * The icon to display in the alert.
	 */
	icon?: Icon;
	/**
	 * Whether the alert can be dismissed.
	 * @default false
	 */
	dismissible?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoAlertManifestDefaults = Required<
	Pick<BoAlertProps, 'size' | 'variant' | 'dismissible' | 'role'>
>;

type BoAlertSizeStyleMap = Record<BoAlertSize, string>;
type BoAlertVariantStyleMap = Record<BoAlertVariant, string>;

export interface BoAlertStyleManifest {
	base: string;
	size: BoAlertSizeStyleMap;
	variants: BoAlertVariantStyleMap;
	iconColor: BoAlertVariantStyleMap;
	titleSize: BoAlertSizeStyleMap;
	contentSize: BoAlertSizeStyleMap;
	iconSize: BoAlertSizeStyleMap;
	closeButton: {
		base: string;
		hover: string;
	};
}

export type AlertManifest = ComponentManifest<BoAlertStyleManifest, BoAlertManifestDefaults>;
