import { HTMLAttributes } from 'vue';
import { BoFontSize } from '../definitions/index.js';
import { ComponentManifest } from '../manifests/index.js';

export type BoAvatarSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoAvatarShape =
	| 'circle'
	| 'flat'
	| 'rounded'
	| 'outline-flat'
	| 'outline-rounded'
	| 'outline-circle';

export type BoAvatarVariant = 'primary' | 'secondary' | 'danger' | 'warning' | 'success' | 'dark';

export type BoAvatarType = 'image' | 'initials';

export type BoAvatarIndicatorPosition = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export type BoAvatarIndicatorStatus = 'online' | 'offline' | 'busy' | 'away' | 'none';

export interface BoAvatarData {
	/** Alt text for the avatar image. */
	alt?: string;
	/** Source URL for the avatar image. */
	src?: string;
	/** Label text for initials display. */
	label?: string;
}

export interface BoAvatarColor {
	/** Custom background color for the avatar */
	bgColor?: string;
	/** Custom text color for the avatar */
	textColor?: string;
}

export interface BoAvatarIndicator {
	/** The status of the indicator. */
	status?: BoAvatarIndicatorStatus;
	/** The position of the indicator. */
	position?: BoAvatarIndicatorPosition;
}

export interface BoAvatarProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: string;
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** Avatar data containing src, alt, and label. */
	data: BoAvatarData;
	/**
	 * The type of avatar to display.
	 * @default 'initials'
	 */
	type?: BoAvatarType;
	/**
	 * The shape of the avatar.
	 * @default 'rounded'
	 */
	shape?: BoAvatarShape;
	/**
	 * The size of the avatar.
	 * @default 'default'
	 */
	size?: BoAvatarSize;
	/** Whether the avatar is clickable. */
	clickable?: boolean;
	/** Whether to show a default image when no src or label is provided. */
	withDefaultImage?: boolean;
	/**
	 * The color variant of the avatar.
	 * @default 'primary'
	 */
	variant?: BoAvatarVariant;
	/** Custom color configuration. */
	color?: BoAvatarColor;
	/** Indicator configuration for status display. */
	indicator?: BoAvatarIndicator;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoAvatarSizeStyleMap = Record<BoAvatarSize, string>;
type BoAvatarShapeStyleMap = Record<BoAvatarShape, string>;
type BoAvatarVariantStyleMap = Record<BoAvatarVariant, string>;
type BoAvatarIndicatorStatusStyleMap = Record<BoAvatarIndicatorStatus, string>;
type BoAvatarIndicatorPositionStyleMap = Record<BoAvatarIndicatorPosition, string>;

export interface AvatarStyleManifest {
	base: string;
	size: BoAvatarSizeStyleMap;
	shape: BoAvatarShapeStyleMap;
	variants: {
		filled: BoAvatarVariantStyleMap;
		outline: BoAvatarVariantStyleMap;
	};
	textColor: {
		filled: BoAvatarVariantStyleMap;
		outline: BoAvatarVariantStyleMap;
	};
	indicator: {
		status: BoAvatarIndicatorStatusStyleMap;
		position: BoAvatarIndicatorPositionStyleMap;
		size: BoAvatarSizeStyleMap;
	};
	labelSize: Record<BoAvatarSize, BoFontSize>;
	containers: {
		default: string;
		initials: string;
		image: string;
	};
}

export type AvatarManifest = ComponentManifest<
	AvatarStyleManifest,
	Pick<BoAvatarProps, 'size' | 'shape' | 'variant' | 'type' | 'indicator' | 'role'>
>;
