import { HTMLAttributes } from 'vue';
import { BoFontSize } from '../definitions/index.js';
import { ComponentManifest } from '../manifests/index.js';

export type BoAvatarSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoAvatarKind =
	| 'default'
	| 'flat'
	| 'circle'
	| 'outline-flat'
	| 'outline-default'
	| 'outline-circle';

export type BoAvatarVariant =
	| 'primary'
	| 'secondary'
	| 'destructive'
	| 'warning'
	| 'success'
	| 'dark';

export type BoAvatarIndicatorPosition = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export type BoAvatarIndicatorKind = 'online' | 'offline' | 'busy' | 'away' | 'none';

export interface BoAvatarColor {
	/** Custom background color for the avatar */
	bgColor?: string;
	/** Custom text color for the avatar */
	textColor?: string;
}

export interface BoAvatarIndicator {
	/** The status of the indicator. */
	status?: BoAvatarIndicatorKind;
	/** The position of the indicator. */
	position?: BoAvatarIndicatorPosition;
}

export interface BoAvatarProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: string;
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The label of the avatar. */
	label?: string;
	/** The data for the avatar. */
	src?: string;
	/** The alt text for the avatar. */
	alt?: string;
	/**
	 * The shape of the avatar.
	 * @default 'rounded'
	 */
	kind?: BoAvatarKind;
	/**
	 * The size of the avatar.
	 * @default 'default'
	 */
	size?: BoAvatarSize;
	/** Whether the avatar is clickable. */
	clickable?: boolean;
	/**
	 * The color variant of the avatar.
	 * @default 'primary'
	 */
	variant?: BoAvatarVariant;
	/** Custom color configuration. */
	customColor?: BoAvatarColor;
	/**
	 * The status of the indicator.
	 *
	 * - 'online' - Green dot
	 * - 'offline' - Gray dot
	 * - 'busy' - Red dot
	 * - 'away' - Yellow dot
	 * - 'none' - No indicator
	 *
	 * @default 'none'
	 */
	indicatorKind?: BoAvatarIndicatorKind;
	/**
	 * The position of the indicator.
	 * @default 'top-right'
	 */
	indicatorPosition?: BoAvatarIndicatorPosition;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoAvatarManifestDefaults = Pick<
	BoAvatarProps,
	'kind' | 'size' | 'variant' | 'role' | 'indicatorKind' | 'indicatorPosition' | 'alt'
>;

type BoAvatarSizeStyleMap = Record<BoAvatarSize, string>;
type BoAvatarKindStyleMap = Record<BoAvatarKind, string>;
type BoAvatarVariantStyleMap = Record<BoAvatarVariant, string>;
type BoAvatarIndicatorStatusStyleMap = Record<BoAvatarIndicatorKind, string>;
type BoAvatarIndicatorPositionStyleMap = Record<BoAvatarIndicatorPosition, string>;

export interface BoAvatarStyleManifest {
	base: string;
	size: BoAvatarSizeStyleMap;
	kind: BoAvatarKindStyleMap;
	variants: {
		filled: BoAvatarVariantStyleMap;
		outline: BoAvatarVariantStyleMap;
	};
	textColor: {
		filled: BoAvatarVariantStyleMap;
		outline: BoAvatarVariantStyleMap;
	};
	indicator: {
		status: BoAvatarIndicatorStatusStyleMap;
		position: BoAvatarIndicatorPositionStyleMap;
		size: BoAvatarSizeStyleMap;
	};
	labelSize: Record<BoAvatarSize, BoFontSize>;
}

export type AvatarManifest = ComponentManifest<BoAvatarStyleManifest, BoAvatarManifestDefaults>;
