import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { BoLoaderType } from './bo-loader.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoButtonVariant =
	| 'primary'
	| 'secondary'
	| 'success'
	| 'warning'
	| 'destructive'
	| 'light'
	| 'dark';

export type BoButtonSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoButtonKind = 'filled' | 'outline' | 'ghost' | 'link';

export type BoButtonShape = 'default' | 'pill' | 'flat';

export interface BoButtonProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLButtonElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the button.
	 * @default 'default'
	 */
	size?: BoButtonSize;
	/**
	 * The variant of the button. This determines
	 * the color properties of the button.
	 *
	 * @default 'primary'
	 */
	variant?: BoButtonVariant;
	/**
	 * Whether the button is disabled. If so
	 * user interactions won't register.
	 */
	disabled?: boolean;
	/**
	 * Whether the button is loading. If so
	 * the button will display a loader before
	 * the label.
	 */
	isLoading?: boolean;
	/**
	 * Determines the type of loader to display when the button is loading.
	 * @default 'spinner'
	 */
	loaderType?: BoLoaderType;
	/**
	 * The kind of the button.
	 *
	 * - filled: A button with a background color.
	 * - outline: A button with a border and no background color.
	 * - ghost: A button with subtle hover effects and no background.
	 * - link: A button styled as a link with no background color or border.
	 *
	 * @default 'filled'
	 */
	kind?: BoButtonKind;
	/**
	 * The shape of the button.
	 *
	 * - default: A button with slightly rounded corners.
	 * - pill: A button with fully rounded corners.
	 * - flat: A button with no rounded corners.
	 *
	 * @default 'default'
	 *
	 */
	shape?: BoButtonShape;
	/**
	 * Whether the button is pressed (for toggle buttons).
	 * Sets aria-pressed attribute for accessibility.
	 */
	pressed?: boolean;
	/**
	 * The type of the button.
	 * @default 'button'
	 */
	type?: HTMLButtonElement['type'];
	/** The text content of the button. */
	label?: string;
	/** Whether the button is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Custom color for the button background (CSS variable, hex, rgb, rgba). */
	customColor?: {
		background?: string;
		border?: string;
		text?: string;
	};
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
	/**
	 * Indicates the current "expanded" state of control.
	 * Used for buttons that control collapsible content.
	 */
	ariaExpanded?: HTMLAttributes['aria-expanded'];
	/** Indicates that the element has a popup context menu or sub-level menu. */
	ariaHasPopup?: HTMLAttributes['aria-haspopup'];
	/** Indicates the current "pressed" state of toggle buttons. */
	ariaPressed?: HTMLAttributes['aria-pressed'];
	/** Indicates whether the element is currently selected. */
	ariaSelected?: HTMLAttributes['aria-selected'];
	/**
	 * Indicates if the element is currently disabled.
	 * Prefer using the disabled prop instead.
	 */
	ariaDisabled?: HTMLAttributes['aria-disabled'];
	/** Indicates that an element will be updated, and describes the types of updates the user agents,
	 * assistive technologies, and user can expect from the live region.
	 *
	 * - off: The element is not exposed to an assistive technology.
	 * - polite: The element is exposed to an assistive technology that "actively" indicates that user input will occur.
	 * - assertive: The element is exposed to an assistive technology that "passively" indicates that user input will occur.
	 *
	 * @default 'polite'
	 */
	ariaLive?: HTMLAttributes['aria-live'];
	/** Tab index of the element. */
	tabIndex?: HTMLAttributes['tabindex'];
	/**
	 * Keyboard shortcut to activate or focus the element.
	 */
	accessKey?: HTMLAttributes['accesskey'];
}

type BoButtonSizeStyleMap = Record<BoButtonSize, string>;
type BoButtonVariantStyleMap = Record<BoButtonVariant, string>;
type BoButtonShapeStyleMap = Record<BoButtonShape, string>;

export interface ButtonStyleManifest {
	base: string;
	width: {
		default: string;
		fullWidth: string;
	};
	shape: BoButtonShapeStyleMap;
	shadow: BoButtonShapeStyleMap;
	size: BoButtonSizeStyleMap;
	iconOnlySize: BoButtonSizeStyleMap;
	variants: {
		filled: BoButtonVariantStyleMap;
		outline: BoButtonVariantStyleMap;
		ghost: BoButtonVariantStyleMap;
		link: BoButtonVariantStyleMap;
	};
	states: {
		loading: string;
		pressed: string;
		focus: string;
	};
	content: {
		container: string;
		label: string;
		prefixIcon: string;
		suffixIcon: string;
		loader: string;
	};
	dataAttributes: {
		slot: string;
		variant: string;
		size: string;
		disabled: string;
		loading: string;
	};
}

export type ButtonManifest = ComponentManifest<
	ButtonStyleManifest,
	Pick<
		BoButtonProps,
		'size' | 'variant' | 'shape' | 'disabled' | 'isLoading' | 'loaderType' | 'role' | 'type'
	>
>;
