import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { BoLoaderType } from './bo-loader.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoButtonVariant =
	| 'primary'
	| 'secondary'
	| 'success'
	| 'warning'
	| 'danger'
	| 'dark'
	| 'purple'
	| 'teal';

export type BoButtonSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoButtonKind = 'default' | 'outline' | 'pill';

export type BoButtonShape = 'default' | 'pill' | 'outline';

export interface BoButtonProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLButtonElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the button.
	 * @default 'default'
	 */
	size?: BoButtonSize;
	/**
	 * The variant of the button. This determines
	 * the color properties of the button.
	 *
	 * @default 'primary'
	 */
	variant?: BoButtonVariant;
	/**
	 * Whether the button is disabled. If so
	 * user interactions won't register.
	 */
	disabled?: boolean;
	/**
	 * Whether the button is loading. If so
	 * the button will display a loader before
	 * the label.
	 */
	isLoading?: boolean;
	/**
	 * Determines the type of loader to display when the button is loading.
	 * @default 'spinner'
	 */
	loaderType?: BoLoaderType;
	/**
	 * The kind of the button.
	 *
	 * - default: A button with a background color and rounded corners.
	 * - outline: A button with a border and no background color.
	 * - pill: A button with a background color and fully rounded corners.
	 *
	 * @default 'default'
	 */
	kind?: BoButtonKind;
	/**
	 * The shape of the button (deprecated - use kind instead).
	 *
	 * - default: A button with slightly rounded corners.
	 * - pill: A button with fully rounded corners.
	 * - outline: A button with a border.
	 *
	 * @default 'default'
	 * @deprecated Use kind prop instead
	 */
	shape?: BoButtonShape;
	/**
	 * Whether the button is pressed (for toggle buttons).
	 * Sets aria-pressed attribute for accessibility.
	 */
	pressed?: boolean;
	/**
	 * The type of the button.
	 * @default 'button'
	 */
	type?: HTMLButtonElement['type'];
	/** The text content of the button. */
	label?: string;
	/** Whether the button is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Custom color for the button background (CSS variable, hex, rgb, rgba). */
	customColor?: {
		background?: string;
		border?: string;
		text?: string;
	};
	/** The name of the button. */
	name?: HTMLButtonElement['name'];
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
	/**
	 * Indicates the current "expanded" state of control.
	 * Used for buttons that control collapsible content.
	 */
	ariaExpanded?: HTMLAttributes['aria-expanded'];
	/** Indicates that the element has a popup context menu or sub-level menu. */
	ariaHasPopup?: HTMLAttributes['aria-haspopup'];
	/**
	 * Indicates if the element is currently disabled.
	 * Prefer using the disabled prop instead.
	 */
	ariaDisabled?: HTMLAttributes['aria-disabled'];
	/** Indicates that an element will be updated, and describes the types of updates the user agents,
	 * assistive technologies, and user can expect from the live region.
	 *
	 * - off: The element is not exposed to an assistive technology.
	 * - polite: The element is exposed to an assistive technology that "actively" indicates that user input will occur.
	 * - assertive: The element is exposed to an assistive technology that "passively" indicates that user input will occur.
	 *
	 * @default 'polite'
	 */
	ariaLive?: HTMLAttributes['aria-live'];
	/** Tab index of the element. */
	tabIndex?: HTMLAttributes['tabindex'];
	/**
	 * Keyboard shortcut to activate or focus the element.
	 */
	accessKey?: HTMLAttributes['accesskey'];
}

type BoButtonManifestDefaults = Pick<
	BoButtonProps,
	'kind' | 'size' | 'variant' | 'shape' | 'loaderType' | 'type' | 'role'
>;

type BoButtonSizeStyleMap = Record<BoButtonSize, string>;
type BoButtonVariantStyleMap = Record<BoButtonVariant, string>;
type BoButtonShapeStyleMap = Record<BoButtonShape, string>;

export interface BoButtonStyleManifest {
	base: string;
	shape: BoButtonShapeStyleMap;
	size: BoButtonSizeStyleMap;
	iconOnlySize: BoButtonSizeStyleMap;
	variants: Record<BoButtonKind, BoButtonVariantStyleMap>;
	textColor: Record<BoButtonKind, BoButtonVariantStyleMap>;
	fontSize: Record<BoButtonSize, string>;
	iconSize: Record<BoButtonSize, string>;
}

export type ButtonManifest = ComponentManifest<BoButtonStyleManifest, BoButtonManifestDefaults>;
