import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { BoFontSize } from './bo-text.js';
import { BoIconSize } from './bo-icon.js';
import { ComponentManifest } from '../manifests/types.js';
import { BoCursor } from './component-types.js';

export type BoBadgeVariant =
	| 'primary'
	| 'secondary'
	| 'destructive'
	| 'warning'
	| 'success'
	| 'light'
	| 'black';

export type BoBadgeKind = 'default' | 'outline';

export type BoBadgeShape = 'default' | 'pill' | 'flat' | 'circle';

export type BoBadgeSize = 'sm' | 'default' | 'lg';

export interface BoBadgeProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLSpanElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The label text to display on the badge. */
	label?: string;
	/**
	 * The type of the badge (filled or outline).
	 * @default 'default'
	 */
	kind?: BoBadgeKind;
	/**
	 * The size of the badge.
	 * @default 'default'
	 */
	size?: BoBadgeSize;
	/**
	 * The shape of the badge.
	 * @default 'default'
	 */
	shape?: BoBadgeShape;
	/**
	 * The color variant of the badge.
	 * @default 'primary'
	 */
	variant?: BoBadgeVariant;
	/** The cursor style of the badge. */
	cursor?: BoCursor;
	/** The custom background color for the badge. */
	customColor?: HTMLSpanElement['style']['color'];
	/** The custom text color for the badge. */
	customTextColor?: string;
	/** The prefix icon of the badge. */
	prefixIcon?: Icon;
	/** The suffix icon of the badge. */
	suffixIcon?: Icon;
	/** The role of the element. */
	role?: HTMLSpanElement['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLSpanElement['ariaLabel'];
}

type BoBadgeManifestDefaults = Pick<
	BoBadgeProps,
	'kind' | 'size' | 'shape' | 'variant' | 'role' | 'cursor'
>;

type BoBadgeSizeStyleMap = Record<BoBadgeSize, string>;
type BoBadgeShapeStyleMap = Record<BoBadgeShape, string>;
type BoBadgeVariantStyleMap = Record<BoBadgeVariant, string>;

export interface BoBadgeStyleManifest {
	base: string;
	shape: BoBadgeShapeStyleMap;
	size: {
		default: BoBadgeSizeStyleMap;
		circle: BoBadgeSizeStyleMap;
	};
	variants: {
		filled: BoBadgeVariantStyleMap;
		outline: BoBadgeVariantStyleMap;
	};
	textColor: {
		filled: BoBadgeVariantStyleMap;
		outline: BoBadgeVariantStyleMap;
	};
	fontSize: Record<BoBadgeSize, BoFontSize>;
	iconSize: Record<BoBadgeSize, BoIconSize>;
}

export type BadgeManifest = ComponentManifest<BoBadgeStyleManifest, BoBadgeManifestDefaults>;
