import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';
import { BoButtonSize, BoButtonVariant } from './bo-button.js';

export type BoButtonGroupOrientation = 'horizontal' | 'vertical';

export interface BoButtonGroupProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The orientation of the button group.
	 * @default 'horizontal'
	 */
	orientation?: BoButtonGroupOrientation;
	/**
	 * The size to apply to all buttons in the group.
	 */
	size?: BoButtonSize;
	/**
	 * The variant to apply to all buttons in the group.
	 */
	variant?: BoButtonVariant;
	/**
	 * Whether the button group should take full width.
	 * @default false
	 */
	fullWidth?: boolean;
	/**
	 * Whether buttons should be attached (no gap between them).
	 * @default true
	 */
	attached?: boolean;
	/**
	 * The role of the button group element.
	 * @default 'group'
	 */
	role?: HTMLAttributes['role'];
	/**
	 * The selected button value(s). Can be a single value or array for multiple selection.
	 */
	modelValue?: string | number | (string | number)[];
	/**
	 * Whether multiple buttons can be selected at once.
	 * @default false
	 */
	multiple?: boolean;
	/**
	 * Whether selection is required (at least one button must be selected).
	 * @default false
	 */
	required?: boolean;
}

type BoButtonGroupManifestDefaults = Pick<
	BoButtonGroupProps,
	'orientation' | 'fullWidth' | 'attached' | 'role' | 'multiple' | 'required'
>;

type BoButtonGroupOrientationStyleMap = Record<BoButtonGroupOrientation, string>;

export interface BoButtonGroupStyleManifest {
	base: string;
	orientation: BoButtonGroupOrientationStyleMap;
	fullWidth: string;
	attached: {
		base: string;
		orientation: BoButtonGroupOrientationStyleMap;
		first: BoButtonGroupOrientationStyleMap;
		middle: BoButtonGroupOrientationStyleMap;
		last: BoButtonGroupOrientationStyleMap;
		single: BoButtonGroupOrientationStyleMap;
	};
	selected: string;
}

export type ButtonGroupManifest = ComponentManifest<
	BoButtonGroupStyleManifest,
	BoButtonGroupManifestDefaults
>;
