import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { BoFontSize } from './bo-text.js';
import { BoIconSize } from './bo-icon.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoBadgeVariant =
	| 'primary'
	| 'secondary'
	| 'destructive'
	| 'warning'
	| 'success'
	| 'light'
	| 'dark';

export type BoBadgeType = 'default' | 'outline';

export type BoBadgeShape = 'default' | 'pill' | 'flat' | 'circle';

export type BoBadgeSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export interface BoBadgeProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: string;
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The label text to display on the badge. */
	label?: string;
	/**
	 * The type of the badge (filled or outline).
	 * @default 'default'
	 */
	type?: BoBadgeType;
	/**
	 * The size of the badge.
	 * @default 'default'
	 */
	size?: BoBadgeSize;
	/**
	 * The shape of the badge.
	 * @default 'default'
	 */
	shape?: BoBadgeShape;
	/**
	 * The color variant of the badge.
	 * @default 'primary'
	 */
	variant?: BoBadgeVariant;
	/** Icon configuration for prefix and suffix icons. */
	icon?: {
		prefix?: Icon;
		suffix?: Icon;
	};
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoBadgeSizeStyleMap = Record<BoBadgeSize, string>;
type BoBadgeShapeStyleMap = Record<BoBadgeShape, string>;
type BoBadgeVariantStyleMap = Record<BoBadgeVariant, string>;

export interface BadgeStyleManifest {
	base: string;
	shape: BoBadgeShapeStyleMap;
	size: {
		default: BoBadgeSizeStyleMap;
		circle: BoBadgeSizeStyleMap;
	};
	variants: {
		default: BoBadgeVariantStyleMap;
		outline: BoBadgeVariantStyleMap;
	};
	fontSize: Record<BoBadgeSize, BoFontSize>;
	iconSize: Record<BoBadgeSize, BoIconSize>;
	containers: {
		prefixIcon: string;
		suffixIcon: string;
	};
}

export type BadgeManifest = ComponentManifest<
	BadgeStyleManifest,
	Pick<BoBadgeProps, 'size' | 'shape' | 'variant' | 'role' | 'type'>
>;
