import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoCarouselOrientation = 'horizontal' | 'vertical';

export interface BoCarouselProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The current active slide index.
	 * @default 0
	 */
	modelValue?: number;
	/**
	 * The orientation of the carousel.
	 * @default 'horizontal'
	 */
	orientation?: BoCarouselOrientation;
	/**
	 * Whether the carousel should auto-play.
	 * @default false
	 */
	autoplay?: boolean;
	/**
	 * Auto-play interval in milliseconds.
	 * @default 3000
	 */
	interval?: number;
	/**
	 * Whether the carousel should loop.
	 * @default true
	 */
	loop?: boolean;
	/**
	 * Whether to show navigation arrows.
	 * @default true
	 */
	showArrows?: boolean;
	/**
	 * Whether to show indicators/dots.
	 * @default true
	 */
	showIndicators?: boolean;
	/**
	 * Whether to pause autoplay on hover.
	 * @default true
	 */
	pauseOnHover?: boolean;
	/**
	 * The role of the carousel element.
	 * @default 'region'
	 */
	role?: HTMLAttributes['role'];
}

export interface BoCarouselItemProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The role of the carousel item element.
	 * @default 'group'
	 */
	role?: HTMLAttributes['role'];
}

type BoCarouselManifestDefaults = Pick<
	BoCarouselProps,
	| 'modelValue'
	| 'orientation'
	| 'autoplay'
	| 'interval'
	| 'loop'
	| 'showArrows'
	| 'showIndicators'
	| 'pauseOnHover'
	| 'role'
>;

type BoCarouselItemManifestDefaults = Pick<BoCarouselItemProps, 'role'>;

type BoCarouselOrientationStyleMap = Record<BoCarouselOrientation, string>;

export interface BoCarouselStyleManifest {
	base: string;
	viewport: {
		base: string;
		orientation: BoCarouselOrientationStyleMap;
	};
	container: {
		base: string;
		orientation: BoCarouselOrientationStyleMap;
	};
	item: {
		base: string;
		orientation: BoCarouselOrientationStyleMap;
	};
	controls: {
		base: string;
		arrow: {
			base: string;
			orientation: BoCarouselOrientationStyleMap;
			prev: BoCarouselOrientationStyleMap;
			next: BoCarouselOrientationStyleMap;
		};
		indicators: {
			base: string;
			orientation: BoCarouselOrientationStyleMap;
			indicator: string;
			active: string;
		};
	};
}

export type CarouselManifest = ComponentManifest<
	BoCarouselStyleManifest,
	BoCarouselManifestDefaults
>;
export type CarouselItemManifest = ComponentManifest<
	BoCarouselStyleManifest,
	BoCarouselItemManifestDefaults
>;
