import { HTMLAttributes } from 'vue';
import { ComponentManifest, ManifestDefaults } from '../manifests/types.js';

export interface BoCardProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The title displayed in the card header. */
	title?: string;
	/** A short description displayed below the title. */
	description?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoCardManifestDefaults = ManifestDefaults<BoCardProps, never>;

export interface BoCardStyleManifest {
	readonly base: 'bo-card';
	readonly header: 'bo-card__header';
	readonly title: 'bo-card__title';
	readonly description: 'bo-card__description';
	readonly media: 'bo-card__media';
	readonly body: 'bo-card__body';
	readonly footer: 'bo-card__footer';
}

export type CardManifest = ComponentManifest<BoCardStyleManifest, BoCardManifestDefaults, 'Card'>;
