import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoCheckboxSize = 'sm' | 'default' | 'lg';

export interface BoCheckboxProps {
	/**
	 * The id of the element. Autogenerated if not provided.
	 */
	id?: string;
	/**
	 * The data test id of the element. Autogenerated if not provided.
	 */
	dataTestId?: string;
	/** Whether the checkbox is disabled. */
	disabled?: boolean;
	/** The name submitted with the checkbox. */
	name?: HTMLInputElement['name'];
	/** The value submitted with the checkbox. */
	value?: HTMLInputElement['value'];
	/** Whether the checkbox is in an indeterminate state. */
	indeterminate?: boolean;
	/** The label text for the checkbox. */
	label?: string;
	/**
	 * The size of the checkbox.
	 * @default 'default'
	 */
	size?: BoCheckboxSize;
	/** Whether the checkbox is required. */
	required?: boolean;
	/** Hint message displayed below the checkbox. */
	hint?: string;
	/** Error message displayed below the checkbox. */
	error?: string;
	/** The role of the checkbox control. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the checkbox control. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Identifies the element that describes the checkbox control. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoCheckboxManifestDefaults = Pick<BoCheckboxProps, 'size'>;

type BoCheckboxSizeStyleMap = Record<BoCheckboxSize, string>;

interface BoCheckboxStyleManifest {
	base: string;
	container: string;
	input: string;
	box: BoCheckboxSizeStyleMap;
	icon: BoCheckboxSizeStyleMap;
	labelGroup: string;
	label: string;
	required: string;
	helpers: {
		container: string;
		error: string;
		hint: string;
	};
}

export type CheckboxManifest = ComponentManifest<
	BoCheckboxStyleManifest,
	BoCheckboxManifestDefaults
>;
