import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';
import { BoCursor } from './component-types.js';

export type BoCardVariant = 'default' | 'outlined' | 'elevated';

export type BoCardSize = 'sm' | 'default' | 'lg';

export interface BoCardPadding {
	top?: boolean;
	right?: boolean;
	bottom?: boolean;
	left?: boolean;
}

export interface BoCardProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLDivElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The variant of the card.
	 * @default 'default'
	 */
	variant?: BoCardVariant;
	/**
	 * The size of the card.
	 * @default 'default'
	 */
	size?: BoCardSize;
	/**
	 * The title of the card.
	 */
	title?: string;
	/**
	 * The description of the card.
	 */
	description?: string;
	/** The cursor to use when hovering over the card. */
	cursor?: BoCursor;
	/**
	 * Custom padding configuration.
	 */
	padding?: BoCardPadding;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoCardManifestDefaults = Pick<BoCardProps, 'variant' | 'size'>;

type BoCardVariantStyleMap = Record<BoCardVariant, string>;
type BoCardSizeStyleMap = Record<BoCardSize, string>;

export interface BoCardStyleManifest {
	base: string;
	variants: BoCardVariantStyleMap;
	size: BoCardSizeStyleMap;
	clickable: string;
	content: string;
}

export type CardManifest = ComponentManifest<BoCardStyleManifest, BoCardManifestDefaults>;
