import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoCheckboxGroupOrientation = 'horizontal' | 'vertical';

export type BoCheckboxGroupSize = 'sm' | 'default' | 'lg';

export interface BoCheckboxGroupProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The v-model value for the checkbox group (array of selected values).
	 */
	modelValue?: (string | number | boolean)[];
	/**
	 * The orientation of the checkbox group.
	 * @default 'vertical'
	 */
	orientation?: BoCheckboxGroupOrientation;
	/**
	 * The size of the checkboxes in the group.
	 * @default 'default'
	 */
	size?: BoCheckboxGroupSize;
	/**
	 * Whether the checkbox group is disabled.
	 */
	disabled?: boolean;
	/**
	 * Whether the checkbox group is required.
	 */
	required?: boolean;
	/**
	 * The label for the checkbox group.
	 */
	label?: string;
	/**
	 * The description for the checkbox group.
	 */
	description?: string;
	/**
	 * The error message for the checkbox group.
	 */
	error?: string;
	/**
	 * The role of the checkbox group element.
	 * @default 'group'
	 */
	role?: HTMLAttributes['role'];
}

type BoCheckboxGroupManifestDefaults = Pick<BoCheckboxGroupProps, 'orientation' | 'size' | 'role'>;

type BoCheckboxGroupOrientationStyleMap = Record<BoCheckboxGroupOrientation, string>;

export interface BoCheckboxGroupStyleManifest {
	base: string;
	orientation: BoCheckboxGroupOrientationStyleMap;
	label: string;
	description: string;
	error: string;
	errorIcon: string;
}

export type CheckboxGroupManifest = ComponentManifest<
	BoCheckboxGroupStyleManifest,
	BoCheckboxGroupManifestDefaults
>;
