import { InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoCheckboxSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoCheckboxState = 'default' | 'valid' | 'invalid';

export interface BoCheckboxProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the checkbox.
	 * @default 'default'
	 */
	size?: BoCheckboxSize;
	/**
	 * The state of the checkbox.
	 * @default 'default'
	 */
	state?: BoCheckboxState;
	/**
	 * Whether the checkbox is checked.
	 * @default false
	 */
	checked?: boolean;
	/**
	 * Whether the checkbox is indeterminate.
	 * @default false
	 */
	indeterminate?: boolean;
	/**
	 * The label of the checkbox.
	 */
	label?: string;
	/**
	 * Description for the checkbox.
	 */
	description?: string;
	/**
	 * Error message to display when in invalid state.
	 */
	error?: string;
	/**
	 * Whether the checkbox is required.
	 */
	required?: boolean;
	/**
	 * The name of the checkbox.
	 */
	name?: HTMLInputElement['name'];
	/**
	 * Whether the checkbox is disabled.
	 */
	disabled?: HTMLInputElement['disabled'];
	/**
	 * The value of the checkbox.
	 */
	value?: string | number | boolean;
}

export interface CheckboxManifest extends ComponentManifest<
	{
		base: string;
		container: string;
		input: {
			base: string;
			size: Record<BoCheckboxSize, string>;
			state: Record<BoCheckboxState, string>;
			disabled: string;
		};
		checkmark: {
			base: string;
			size: Record<BoCheckboxSize, string>;
		};
		labelContainer: string;
		label: {
			base: string;
			size: Record<BoCheckboxSize, string>;
			disabled: string;
		};
		description: {
			base: string;
			size: Record<BoCheckboxSize, string>;
		};
		error: {
			base: string;
			size: Record<BoCheckboxSize, string>;
		};
	},
	{
		size: BoCheckboxSize;
		state: BoCheckboxState;
		checked: boolean;
		indeterminate: boolean;
	}
> {}
