import { HTMLAttributes } from 'vue';
import { ComponentManifest, ManifestDefaults } from '../manifests/types.js';

export type BoCardVariant =
	| 'default'
	| 'primary'
	| 'secondary'
	| 'destructive'
	| 'warning'
	| 'success';

export interface BoCardProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * The visual variant of the card which sets the accent border color.
	 * @default 'default'
	 */
	variant?: BoCardVariant;
	/** The title displayed in the card header. */
	title?: string;
	/** A short description displayed below the title. */
	description?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoCardManifestDefaults = ManifestDefaults<BoCardProps, 'variant'>;

type BoCardVariantStyleMap = Record<BoCardVariant, string>;

export interface BoCardStyleManifest {
	readonly base: 'bo-card';
	readonly variant: BoCardVariantStyleMap;
	readonly header: 'bo-card__header';
	readonly title: 'bo-card__title';
	readonly description: 'bo-card__description';
	readonly body: 'bo-card__body';
	readonly footer: 'bo-card__footer';
}

export type CardManifest = ComponentManifest<BoCardStyleManifest, BoCardManifestDefaults, 'Card'>;
