import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoDividerVariant =
	| 'neutral'
	| 'primary'
	| 'secondary'
	| 'accent'
	| 'success'
	| 'warning'
	| 'info'
	| 'error';

export type BoDividerOrientation = 'vertical' | 'horizontal';

export type BoDividerPlacement = 'start' | 'center' | 'end';

export interface BoDividerProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLDivElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The color variant of the divider.
	 * @default 'neutral'
	 */
	variant?: BoDividerVariant;
	/**
	 * The orientation of the divider.
	 * @default 'vertical'
	 */
	orientation?: BoDividerOrientation;
	/**
	 * The placement of the divider text.
	 * @default 'center'
	 */
	placement?: BoDividerPlacement;
	/**
	 * Optional text content for the divider.
	 */
	text?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoDividerManifestDefaults = Pick<BoDividerProps, 'variant' | 'orientation' | 'placement'>;

type BoDividerVariantStyleMap = Record<BoDividerVariant, string>;
type BoDividerOrientationStyleMap = Record<BoDividerOrientation, string>;
type BoDividerPlacementStyleMap = Record<BoDividerPlacement, string>;

export interface BoDividerStyleManifest {
	base: string;
	variants: BoDividerVariantStyleMap;
	orientations: BoDividerOrientationStyleMap;
	placements: BoDividerPlacementStyleMap;
}

export type DividerManifest = ComponentManifest<BoDividerStyleManifest, BoDividerManifestDefaults>;
