import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoDividerVariant =
	| 'primary'
	| 'secondary'
	| 'destructive'
	| 'warning'
	| 'success'
	| 'dark';

export type BoDividerType = 'default' | 'dotted' | 'dashed';

export interface BoDividerProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLHRElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The variant of the divider.
	 * @default 'secondary'
	 */
	variant?: BoDividerVariant;
	/**
	 * The type of the divider.
	 * @default 'default'
	 */
	type?: BoDividerType;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoDividerManifestDefaults = Pick<BoDividerProps, 'variant' | 'type'>;

type BoDividerVariantStyleMap = Record<BoDividerVariant, string>;
type BoDividerTypeStyleMap = Record<BoDividerType, string>;

export interface BoDividerStyleManifest {
	base: string;
	variants: BoDividerVariantStyleMap;
	types: BoDividerTypeStyleMap;
}

export type DividerManifest = ComponentManifest<BoDividerStyleManifest, BoDividerManifestDefaults>;
