import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { Icon } from './index.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoInputType = InputHTMLAttributes['type'];

export type BoInputState = 'default' | 'valid' | 'invalid';

export interface BoInputProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The state of the input.
	 * @default 'default'
	 */
	state?: BoInputState;
	/**
	 * The type of the input.
	 * @default 'text'
	 */
	type?: BoInputType;
	/** The placeholder of the input. */
	placeholder?: HTMLInputElement['placeholder'];
	/** The label of the input. */
	label?: string;
	/** Description for the input. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** Hint message to display below the input. */
	hint?: string;
	/** Whether the input is required. */
	required?: boolean;
	/** The name of the input. */
	name?: HTMLInputElement['name'];
	/** Whether the input is disabled. */
	disabled?: HTMLInputElement['disabled'];
	/** Whether the input is read-only. */
	readOnly?: HTMLInputElement['readOnly'];
	/** Whether the input is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Whether the input should autofocus */
	autofocus?: HTMLInputElement['autofocus'];
	/** Whether to show toggle button for password input */
	revealPassword?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoInputManifestDefaults = Pick<BoInputProps, 'state' | 'type' | 'role'>;

type BoInputStateStyleMap = Record<BoInputState, string>;

interface BoInputStyleManifest {
	base: string;
	container: {
		base: string;
		disabled: string;
	};
	input: {
		base: string;
	};
	state: BoInputStateStyleMap;
	icons: {
		prefix: string;
		suffix: string;
	};
	labels: {
		container: string;
		label: string;
		required: string;
	};
	helpers: {
		container: string;
		error: string;
	};
}

export type InputManifest = ComponentManifest<BoInputStyleManifest, BoInputManifestDefaults>;
