import { ComponentManifest } from '../manifests/types.js';
import { Icon } from './index.js';

export type BoInputType =
	| 'button'
	| 'checkbox'
	| 'color'
	| 'date'
	| 'datetime-local'
	| 'email'
	| 'file'
	| 'hidden'
	| 'image'
	| 'month'
	| 'number'
	| 'password'
	| 'radio'
	| 'range'
	| 'reset'
	| 'search'
	| 'submit'
	| 'tel'
	| 'text'
	| 'time'
	| 'url'
	| 'week';

export type BoInputState = 'default' | 'valid' | 'invalid';

export interface BoInputProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: string;
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The state of the input.
	 * @default 'default'
	 */
	state?: BoInputState;
	/**
	 * The type of the input.
	 * @default 'text'
	 */
	type?: BoInputType;
	/** The placeholder of the input. */
	placeholder?: string;
	/** The label of the input. */
	label?: string;
	/** Description for the input. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** Hint message to display below the input. */
	hint?: string;
	/** Whether the input is required. */
	required?: boolean;
	/** The name of the input. */
	name?: string;
	/** Browser autofill and password-manager hint. */
	autocomplete?: string;
	/** Whether the input is disabled. */
	disabled?: boolean;
	/** Whether the input is read-only. */
	readOnly?: boolean;
	/** Whether the input is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Whether the input should autofocus */
	autofocus?: boolean;
	/** Whether to show toggle button for password input */
	revealPassword?: boolean;
	/** The role of the element. */
	role?: string;
	/** Defines a string value that labels the current element. */
	ariaLabel?: string;
	/** Identifies supporting text for the input. */
	ariaDescribedBy?: string;
	/** Overrides the computed invalid state. */
	ariaInvalid?: boolean | 'true' | 'false' | 'grammar' | 'spelling';
}

type BoInputManifestDefaults = Pick<BoInputProps, 'state' | 'type' | 'role'>;

type BoInputStateStyleMap = Record<BoInputState, string>;

interface BoInputStyleManifest {
	base: string;
	container: {
		base: string;
		disabled: string;
	};
	input: {
		base: string;
	};
	state: BoInputStateStyleMap;
	icons: {
		prefix: string;
		suffix: string;
		passwordToggle: string;
	};
	width: {
		default: string;
		full: string;
	};
	labels: {
		container: string;
		label: string;
		required: string;
	};
	helpers: {
		container: string;
		error: string;
		hint: string;
	};
}

export type InputManifest = ComponentManifest<BoInputStyleManifest, BoInputManifestDefaults>;
