import { ComponentManifest } from '../manifests/types.js';

export type BoInputOtpType = 'text' | 'password';
export type BoInputOtpInputMode =
	| 'none'
	| 'text'
	| 'tel'
	| 'url'
	| 'email'
	| 'numeric'
	| 'decimal'
	| 'search';

export interface BoInputOtpProps {
	/** The id of the control. Autogenerated if not provided. */
	id?: string;
	/** The data test id of the control. Autogenerated if not provided. */
	dataTestId?: string;
	/** Number of characters in the one-time password. */
	length?: number;
	/** Whether entered characters are hidden. */
	type?: BoInputOtpType;
	/** Pattern used to validate each character. */
	pattern?: string;
	/** Input keyboard hint. */
	inputMode?: BoInputOtpInputMode;
	/** The form name of the control. */
	name?: string;
	/** Browser autofill hint, defaulting to a one-time code. */
	autocomplete?: string;
	/** The visible label. */
	label?: string;
	/** Description displayed below the control. */
	description?: string;
	/** Error message displayed below the control. */
	error?: string;
	/** Hint displayed below the control. */
	hint?: string;
	/** Whether the control is required. */
	required?: boolean;
	/** Whether the control is disabled. */
	disabled?: boolean;
	/** Whether the control is read-only. */
	readOnly?: boolean;
	/** Whether the first input should receive focus on mount. */
	autofocus?: boolean;
	/** The role of the control. */
	role?: string;
	/** Accessible name for the control. */
	ariaLabel?: string;
	/** Accessible label reference for the control. */
	ariaLabelledBy?: string;
	/** Accessible description reference for the control. */
	ariaDescribedBy?: string;
}

export interface BoInputOtpStyleManifest {
	base: string;
	labels: { container: string; label: string; required: string };
	group: string;
	input: string;
	helpers: { container: string; description: string; error: string; hint: string };
}

export type InputOtpManifest = ComponentManifest<
	BoInputOtpStyleManifest,
	Required<Pick<BoInputOtpProps, 'length' | 'type' | 'inputMode' | 'pattern' | 'role'>>
>;
