import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { BoFontSize, BoIconSize, Icon } from './index.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoInputSize = 'sm' | 'default' | 'lg';

export type BoInputType = InputHTMLAttributes['type'];

export type BoInputState = 'default' | 'valid' | 'invalid';

export type BoInputVariant = 'default' | 'filled';

export interface BoInputPill {
	/** Unique identifier for the pill */
	id: string;
	/** Data test ID for the pill */
	dataTestId: string;
	/** The label text to display on the pill */
	text: string;
	/** Optional icon to display before pill label */
	icon?: Icon;
}

export interface BoInputProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the input.
	 * @default 'default'
	 */
	size?: BoInputSize;
	/**
	 * The state of the input.
	 * @default 'default'
	 */
	state?: BoInputState;
	/**
	 * The variant of the input.
	 * @default 'default'
	 */
	variant?: BoInputVariant;
	/**
	 * The type of the input.
	 * @default 'text'
	 */
	type?: BoInputType;
	/** The placeholder of the input. */
	placeholder?: HTMLInputElement['placeholder'];
	/** The label of the input. */
	label?: string;
	/** Description for the input. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** Hint message to display below the input. */
	hint?: string;
	/** Whether the input is required. */
	required?: boolean;
	/** The name of the input. */
	name?: HTMLInputElement['name'];
	/** Whether the input is disabled. */
	disabled?: HTMLInputElement['disabled'];
	/** Whether the input is read-only. */
	readOnly?: HTMLInputElement['readOnly'];
	/** Whether the input is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Whether the input should autofocus */
	autofocus?: HTMLInputElement['autofocus'];
	/** Array of pill items to display in the input */
	pills?: BoInputPill[];
	/** Whether to enable horizontal scrolling for pills */
	horizontalScroll?: boolean;
	/** Whether to show toggle button for password input */
	revealPassword?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoInputManifestDefaults = Pick<BoInputProps, 'size' | 'state' | 'variant' | 'type' | 'role'>;

type BoInputSizeStyleMap = Record<BoInputSize, string>;
type BoInputStateStyleMap = Record<BoInputState, string>;
type BoInputVariantStyleMap = Record<BoInputVariant, string>;

interface BoInputStyleManifest {
	base: string;
	container: {
		base: string;
		disabled: string;
	};
	input: {
		base: string;
		withPills: string;
	};
	size: BoInputSizeStyleMap;
	padding: BoInputSizeStyleMap;
	state: BoInputStateStyleMap;
	variant: BoInputVariantStyleMap;
	icons: {
		prefix: string;
		suffix: string;
		size: Record<BoInputSize, BoIconSize>;
	};
	inputContainer: {
		base: string;
		horizontalScroll: string;
		flexWrap: string;
		withPrefixIcon: string;
		withSuffixIcon: string;
	};
	labels: {
		container: string;
		label: string;
		required: string;
		fontSize: BoFontSize;
	};
	helpers: {
		container: string;
		error: string;
		fontSize: BoFontSize;
	};
}

export type InputManifest = ComponentManifest<BoInputStyleManifest, BoInputManifestDefaults>;
