import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoLabelSize = 'sm' | 'default' | 'lg';

export interface BoLabelProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The id of the form control this label is associated with. */
	for?: string;
	/**
	 * Whether the associated control is required.
	 * @default false
	 */
	required?: boolean;
	/**
	 * Whether the label is in a disabled state.
	 * @default false
	 */
	disabled?: boolean;
	/**
	 * The size of the label.
	 * @default 'default'
	 */
	size?: BoLabelSize;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoLabelManifestDefaults = Pick<BoLabelProps, 'required' | 'disabled' | 'size'>;

export interface BoLabelStyleManifest {
	base: string;
	required: string;
	disabled: string;
	size: Record<BoLabelSize, string>;
}

export type LabelManifest = ComponentManifest<BoLabelStyleManifest, BoLabelManifestDefaults>;
