import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoModalSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl' | 'full';

export type BoModalPosition = 'center' | 'top' | 'bottom';

export interface BoModalProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * Whether the modal is open.
	 * @default false
	 */
	open?: boolean;
	/**
	 * The size of the modal.
	 * @default 'default'
	 */
	size?: BoModalSize;
	/**
	 * The position of the modal.
	 * @default 'center'
	 */
	position?: BoModalPosition;
	/**
	 * Whether clicking the backdrop closes the modal.
	 * @default true
	 */
	closeOnBackdropClick?: boolean;
	/**
	 * Whether pressing escape closes the modal.
	 * @default true
	 */
	closeOnEscape?: boolean;
	/**
	 * Whether to show the close button.
	 * @default true
	 */
	showCloseButton?: boolean;
	/**
	 * The title of the modal.
	 */
	title?: string;
	/**
	 * Whether to prevent body scroll when modal is open.
	 * @default true
	 */
	preventBodyScroll?: boolean;
	/**
	 * Custom z-index for the modal.
	 * @default 50
	 */
	zIndex?: number;
}

export interface ModalManifest extends ComponentManifest<
	{
		backdrop: string;
		container: string;
		content: {
			base: string;
			size: Record<BoModalSize, string>;
			position: Record<BoModalPosition, string>;
		};
		header: {
			base: string;
			withCloseButton: string;
		};
		title: string;
		closeButton: string;
		body: string;
		footer: string;
	},
	{
		size: BoModalSize;
		position: BoModalPosition;
		closeOnBackdropClick: boolean;
		closeOnEscape: boolean;
		showCloseButton: boolean;
		preventBodyScroll: boolean;
		zIndex: number;
	}
> {}
