import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoModalVariant = 'default' | 'info' | 'warning' | 'error';

export type BoModalSize = 'sm' | 'default' | 'lg' | 'xl' | 'full';

export interface BoModalProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * Whether the modal is open.
	 * @default false
	 */
	open?: boolean;
	/**
	 * The title displayed in the modal header.
	 */
	title?: string;
	/**
	 * The variant of the modal which determines the header icon and accent color.
	 * @default 'default'
	 */
	variant?: BoModalVariant;
	/**
	 * The size of the modal panel.
	 * @default 'default'
	 */
	size?: BoModalSize;
	/**
	 * Whether clicking the backdrop closes the modal.
	 * @default true
	 */
	closeOnBackdrop?: boolean;
	/**
	 * Whether pressing Escape closes the modal.
	 * @default true
	 */
	closeOnEscape?: boolean;
	/**
	 * Whether to show the close button in the header.
	 * @default true
	 */
	showClose?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoModalManifestDefaults = Pick<
	BoModalProps,
	'variant' | 'size' | 'closeOnBackdrop' | 'closeOnEscape' | 'showClose' | 'role'
>;

type BoModalVariantStyleMap = Record<BoModalVariant, string>;
type BoModalSizeStyleMap = Record<BoModalSize, string>;

interface BoModalStyleManifest {
	backdrop: string;
	wrapper: string;
	panel: {
		base: string;
		size: BoModalSizeStyleMap;
	};
	header: {
		base: string;
		variant: BoModalVariantStyleMap;
	};
	close: string;
	body: string;
	footer: string;
	icon: {
		variant: BoModalVariantStyleMap;
	};
}

export type ModalManifest = ComponentManifest<BoModalStyleManifest, BoModalManifestDefaults>;
