import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoNavbarVariant = 'default' | 'transparent' | 'bordered';

export type BoNavbarSize = 'sm' | 'default' | 'lg';

export interface BoNavbarProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The variant of the navbar.
	 * @default 'default'
	 */
	variant?: BoNavbarVariant;
	/**
	 * The size of the navbar.
	 * @default 'default'
	 */
	size?: BoNavbarSize;
	/**
	 * Whether the navbar is sticky.
	 * @default false
	 */
	sticky?: boolean;
	/**
	 * Whether the navbar has a shadow.
	 * @default true
	 */
	shadow?: boolean;
	/**
	 * Whether the navbar should blur the background.
	 * @default false
	 */
	blur?: boolean;
	/**
	 * The maximum width of the navbar content.
	 * @default 'full'
	 */
	maxWidth?: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'full';
	/**
	 * The role of the navbar element.
	 * @default 'navigation'
	 */
	role?: HTMLAttributes['role'];
}

type BoNavbarManifestDefaults = Pick<
	BoNavbarProps,
	'variant' | 'size' | 'sticky' | 'shadow' | 'blur' | 'maxWidth' | 'role'
>;

type BoNavbarVariantStyleMap = Record<BoNavbarVariant, string>;
type BoNavbarSizeStyleMap = Record<BoNavbarSize, string>;
type BoNavbarMaxWidthStyleMap = Record<NonNullable<BoNavbarProps['maxWidth']>, string>;

export interface BoNavbarStyleManifest {
	base: string;
	variant: BoNavbarVariantStyleMap;
	size: BoNavbarSizeStyleMap;
	sticky: string;
	shadow: string;
	blur: string;
	container: {
		base: string;
		maxWidth: BoNavbarMaxWidthStyleMap;
	};
	content: {
		base: string;
		size: BoNavbarSizeStyleMap;
	};
	brand: string;
	nav: string;
	actions: string;
	mobile: {
		toggle: string;
		menu: string;
		menuOpen: string;
	};
}

export type NavbarManifest = ComponentManifest<BoNavbarStyleManifest, BoNavbarManifestDefaults>;
