import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export interface BoNumberFieldProps {
	/** The id of the control. Autogenerated if not provided. */
	id?: HTMLInputElement['id'];
	/** The data test id of the control. Autogenerated if not provided. */
	dataTestId?: string;
	/** The minimum accepted value. */
	min?: HTMLInputElement['min'];
	/** The maximum accepted value. */
	max?: HTMLInputElement['max'];
	/** The amount changed by the stepper buttons. */
	step?: HTMLInputElement['step'];
	/** Placeholder text. */
	placeholder?: HTMLInputElement['placeholder'];
	/** Input keyboard hint. */
	inputMode?: InputHTMLAttributes['inputmode'];
	/** The visible label. */
	label?: string;
	/** Description displayed below the control. */
	description?: string;
	/** Error message displayed below the control. */
	error?: string;
	/** Hint displayed below the control. */
	hint?: string;
	/** Whether the control is required. */
	required?: boolean;
	/** Whether the control is disabled. */
	disabled?: boolean;
	/** Whether the control is read-only. */
	readOnly?: boolean;
	/** The form name of the control. */
	name?: HTMLInputElement['name'];
	/** Whether the control should receive focus on mount. */
	autofocus?: boolean;
	/** The role of the control. */
	role?: HTMLAttributes['role'];
	/** Accessible name for the control. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Accessible label reference for the control. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Accessible description reference for the control. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

export interface BoNumberFieldStyleManifest {
	base: string;
	labels: { container: string; label: string; required: string };
	container: string;
	input: string;
	button: string;
	buttons: { container: string; decrement: string; increment: string };
	helpers: { container: string; description: string; error: string; hint: string };
}

export type NumberFieldManifest = ComponentManifest<
	BoNumberFieldStyleManifest,
	Record<string, never>
>;
