import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoNavbarVariant = 'floating' | 'solid' | 'minimal';

export type BoNavbarPosition = 'static' | 'sticky' | 'fixed';

export type BoNavbarPadding = 'none' | 'sm' | 'md' | 'lg';

export type BoNavbarMaxWidth = 'full' | 'xl' | 'content';

export type BoNavbarOffset = 'none' | 'sm' | 'md' | 'lg';

export interface BoNavbarProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLAttributes['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** Visual treatment of the navbar. @default 'floating' */
	variant?: BoNavbarVariant;
	/** Positioning strategy for the navbar. @default 'sticky' */
	position?: BoNavbarPosition;
	/** Padding preset for the navbar container. @default 'md' */
	padding?: BoNavbarPadding;
	/** Maximum width of the inner shell. @default 'xl' */
	maxWidth?: BoNavbarMaxWidth;
	/** Top offset when using sticky or fixed positioning. @default 'md' */
	offset?: BoNavbarOffset;
	/** Whether rounded corners are applied. @default true */
	rounded?: boolean;
	/** Whether elevation (shadow) is applied. @default true */
	shadow?: boolean;
	/** Whether borders are applied. @default true */
	border?: boolean;
	/** The role of the navbar element. @default 'navigation' */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoNavbarManifestDefaults = Required<
	Pick<
		BoNavbarProps,
		| 'variant'
		| 'position'
		| 'padding'
		| 'maxWidth'
		| 'offset'
		| 'role'
		| 'rounded'
		| 'shadow'
		| 'border'
	>
>;

type BoNavbarVariantStyleMap = Record<BoNavbarVariant, string>;
type BoNavbarPositionStyleMap = Record<BoNavbarPosition, string>;
type BoNavbarPaddingStyleMap = Record<BoNavbarPadding, string>;
type BoNavbarWidthStyleMap = Record<BoNavbarMaxWidth, string>;
type BoNavbarOffsetStyleMap = Record<BoNavbarOffset, string>;

export interface BoNavbarStyleManifest {
	outer: string;
	shell: string;
	text: string;
	sections: {
		brand: string;
		nav: string;
		actions: string;
	};
	variant: BoNavbarVariantStyleMap;
	position: BoNavbarPositionStyleMap;
	padding: BoNavbarPaddingStyleMap;
	width: BoNavbarWidthStyleMap;
	offset: BoNavbarOffsetStyleMap;
	rounded: string;
	shadow: string;
	border: string;
}

export type NavbarManifest = ComponentManifest<BoNavbarStyleManifest, BoNavbarManifestDefaults>;
