import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoPinInputType = 'text' | 'password';

export interface BoPinInputProps {
	/** The id of the control. Autogenerated if not provided. */
	id?: HTMLInputElement['id'];
	/** The data test id of the control. Autogenerated if not provided. */
	dataTestId?: string;
	/** Number of digits in the PIN. */
	length?: number;
	/** Whether entered digits are hidden. */
	type?: BoPinInputType;
	/** Pattern used to validate each character. */
	pattern?: string;
	/** Input keyboard hint. */
	inputMode?: InputHTMLAttributes['inputmode'];
	/** The form name of the control. */
	name?: HTMLInputElement['name'];
	/** Placeholder shown in empty PIN cells. */
	placeholder?: string;
	/** The visible label. */
	label?: string;
	/** Description displayed below the control. */
	description?: string;
	/** Error message displayed below the control. */
	error?: string;
	/** Hint displayed below the control. */
	hint?: string;
	/** Whether the control is required. */
	required?: boolean;
	/** Whether the control is disabled. */
	disabled?: boolean;
	/** Whether the control is read-only. */
	readOnly?: boolean;
	/** Whether the first input should receive focus on mount. */
	autofocus?: boolean;
	/** The role of the control. */
	role?: HTMLAttributes['role'];
	/** Accessible name for the control. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Accessible label reference for the control. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Accessible description reference for the control. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

export interface BoPinInputStyleManifest {
	base: string;
	labels: { container: string; label: string; required: string };
	group: string;
	input: string;
	helpers: { container: string; description: string; error: string; hint: string };
}

export type PinInputManifest = ComponentManifest<
	BoPinInputStyleManifest,
	Required<Pick<BoPinInputProps, 'length' | 'type' | 'inputMode' | 'pattern'>>
>;
