import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoProgressSize = 'sm' | 'default' | 'lg';

export type BoProgressVariant = 'primary' | 'secondary' | 'success' | 'warning' | 'destructive';

export interface BoProgressProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The current value of the progress (0-100).
	 * @default 0
	 */
	value?: number;
	/**
	 * The maximum value of the progress.
	 * @default 100
	 */
	max?: number;
	/**
	 * The size of the progress bar.
	 * @default 'default'
	 */
	size?: BoProgressSize;
	/**
	 * The variant/color of the progress bar.
	 * @default 'primary'
	 */
	variant?: BoProgressVariant;
	/**
	 * Whether to show the progress value as a label.
	 * @default false
	 */
	showLabel?: boolean;
	/**
	 * Custom label to display instead of percentage.
	 */
	label?: string;
	/**
	 * Whether the progress bar is indeterminate (loading state).
	 * @default false
	 */
	indeterminate?: boolean;
	/**
	 * Whether the progress bar is striped.
	 * @default false
	 */
	striped?: boolean;
	/**
	 * Whether the striped progress bar is animated.
	 * @default false
	 */
	animated?: boolean;
	/**
	 * The role of the progress element.
	 * @default 'progressbar'
	 */
	role?: HTMLAttributes['role'];
}

type BoProgressManifestDefaults = Pick<
	BoProgressProps,
	| 'value'
	| 'max'
	| 'size'
	| 'variant'
	| 'showLabel'
	| 'indeterminate'
	| 'striped'
	| 'animated'
	| 'role'
>;

type BoProgressSizeStyleMap = Record<BoProgressSize, string>;
type BoProgressVariantStyleMap = Record<BoProgressVariant, string>;

export interface BoProgressStyleManifest {
	base: string;
	track: string;
	bar: {
		base: string;
		size: BoProgressSizeStyleMap;
		variant: BoProgressVariantStyleMap;
		striped: string;
		animated: string;
		indeterminate: string;
	};
	label: {
		base: string;
		size: BoProgressSizeStyleMap;
	};
}

export type ProgressManifest = ComponentManifest<
	BoProgressStyleManifest,
	BoProgressManifestDefaults
>;
