import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoRadioGroupOrientation = 'horizontal' | 'vertical';

export interface BoRadioGroupProps {
	/** The id of the group. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the group. Autogenerated if not provided. */
	dataTestId?: string;
	/** The selected radio value. */
	modelValue?: string | number;
	/** The layout direction of the radio items. */
	orientation?: BoRadioGroupOrientation;
	/** Whether all radio items are disabled. */
	disabled?: boolean;
	/** Whether the group requires a selection. */
	required?: boolean;
	/** The shared name of the radio inputs. */
	name?: string;
	/** The role of the group element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the group. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Identifies the element that labels the group. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
}

export interface BoRadioGroupItemProps {
	/** The id of the radio item. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the radio item. Autogenerated if not provided. */
	dataTestId?: string;
	/** The value represented by this radio item. */
	value: string | number;
	/** The visible label of the radio item. */
	label?: string;
	/** Additional descriptive text for the radio item. */
	description?: string;
	/** Whether this radio item is disabled. */
	disabled?: boolean;
	/** The role of the radio control. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the radio control. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Identifies the element that describes the radio control. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

export interface BoRadioGroupStyleManifest {
	base: string;
	orientation: Record<BoRadioGroupOrientation, string>;
}

export interface BoRadioGroupItemStyleManifest {
	base: string;
	input: string;
	indicator: string;
	dot: string;
	labelGroup: string;
	label: string;
	description: string;
}

export type RadioGroupManifest = ComponentManifest<
	BoRadioGroupStyleManifest,
	Pick<BoRadioGroupProps, 'orientation'>
>;

export type RadioGroupItemManifest = ComponentManifest<
	BoRadioGroupItemStyleManifest,
	Record<string, never>
>;
