import { InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoRadioSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoRadioState = 'default' | 'valid' | 'invalid';

export interface BoRadioProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the radio button.
	 * @default 'default'
	 */
	size?: BoRadioSize;
	/**
	 * The state of the radio button.
	 * @default 'default'
	 */
	state?: BoRadioState;
	/**
	 * Whether the radio button is checked.
	 * @default false
	 */
	checked?: boolean;
	/**
	 * The label of the radio button.
	 */
	label?: string;
	/**
	 * Description for the radio button.
	 */
	description?: string;
	/**
	 * Error message to display when in invalid state.
	 */
	error?: string;
	/**
	 * Whether the radio button is required.
	 */
	required?: boolean;
	/**
	 * The name of the radio button group.
	 */
	name?: HTMLInputElement['name'];
	/**
	 * Whether the radio button is disabled.
	 */
	disabled?: HTMLInputElement['disabled'];
	/**
	 * The value of the radio button.
	 */
	value?: string | number | boolean;
}

export interface RadioManifest extends ComponentManifest<
	{
		base: string;
		container: string;
		input: {
			base: string;
			size: Record<BoRadioSize, string>;
			state: Record<BoRadioState, string>;
			disabled: string;
		};
		indicator: {
			base: string;
			size: Record<BoRadioSize, string>;
		};
		labelContainer: string;
		label: {
			base: string;
			size: Record<BoRadioSize, string>;
			disabled: string;
		};
		description: {
			base: string;
			size: Record<BoRadioSize, string>;
		};
		error: {
			base: string;
			size: Record<BoRadioSize, string>;
		};
	},
	{
		size: BoRadioSize;
		state: BoRadioState;
		checked: boolean;
	}
> {}
