import { ComponentManifest } from '../manifests/types.js';

export type BoRadioSize = 'sm' | 'default' | 'lg';

export interface BoRadioProps {
	/**
	 * The id of the element. Autogenerated if not provided.
	 */
	id?: string;
	/**
	 * The data test id of the element. Autogenerated if not provided.
	 */
	dataTestId?: string;
	/** The value associated with this radio option. */
	value: string | number;
	/** Whether the radio is disabled. */
	disabled?: boolean;
	/** The label text for the radio. */
	label?: string;
	/**
	 * The size of the radio.
	 * @default 'default'
	 */
	size?: BoRadioSize;
	/** Whether the radio is required. */
	required?: boolean;
}

type BoRadioManifestDefaults = Pick<BoRadioProps, 'size'>;

type BoRadioSizeStyleMap = Record<BoRadioSize, string>;

interface BoRadioStyleManifest {
	base: string;
	input: BoRadioSizeStyleMap;
	label: string;
}

export type RadioManifest = ComponentManifest<BoRadioStyleManifest, BoRadioManifestDefaults>;
