import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoRadioGroupOrientation = 'horizontal' | 'vertical';

export type BoRadioGroupSize = 'sm' | 'default' | 'lg';

export interface BoRadioGroupProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The v-model value for the radio group.
	 */
	modelValue?: string | number | boolean;
	/**
	 * The name attribute for all radio buttons in the group.
	 */
	name?: string;
	/**
	 * The orientation of the radio group.
	 * @default 'vertical'
	 */
	orientation?: BoRadioGroupOrientation;
	/**
	 * The size of the radio buttons in the group.
	 * @default 'default'
	 */
	size?: BoRadioGroupSize;
	/**
	 * Whether the radio group is disabled.
	 */
	disabled?: boolean;
	/**
	 * Whether the radio group is required.
	 */
	required?: boolean;
	/**
	 * The label for the radio group.
	 */
	label?: string;
	/**
	 * The description for the radio group.
	 */
	description?: string;
	/**
	 * The error message for the radio group.
	 */
	error?: string;
	/**
	 * The role of the radio group element.
	 * @default 'radiogroup'
	 */
	role?: HTMLAttributes['role'];
}

type BoRadioGroupManifestDefaults = Pick<BoRadioGroupProps, 'orientation' | 'size' | 'role'>;

type BoRadioGroupOrientationStyleMap = Record<BoRadioGroupOrientation, string>;

export interface BoRadioGroupStyleManifest {
	base: string;
	orientation: BoRadioGroupOrientationStyleMap;
	label: string;
	description: string;
	error: string;
	errorIcon: string;
}

export type RadioGroupManifest = ComponentManifest<
	BoRadioGroupStyleManifest,
	BoRadioGroupManifestDefaults
>;
