import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoSkeletonVariant = 'text' | 'circle' | 'rect';

export interface BoSkeletonProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * The visual variant (shape) of the skeleton.
	 * @default 'rect'
	 */
	variant?: BoSkeletonVariant;
	/**
	 * Custom width. Accepts any valid CSS size value (e.g. '100px', '4rem').
	 */
	width?: string;
	/**
	 * Custom height. Accepts any valid CSS size value (e.g. '1.25rem', '40px').
	 */
	height?: string;
	/**
	 * Whether the skeleton plays the pulse animation.
	 * @default true
	 */
	animated?: boolean;
	/** The accessible label of the skeleton. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** The role of the element. */
	role?: HTMLAttributes['role'];
}

type BoSkeletonManifestDefaults = Pick<BoSkeletonProps, 'variant' | 'animated' | 'role'>;

export interface BoSkeletonStyleManifest {
	base: string;
	animated: string;
	variant: Record<BoSkeletonVariant, string>;
}

export type SkeletonManifest = ComponentManifest<
	BoSkeletonStyleManifest,
	BoSkeletonManifestDefaults
>;
