import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoSeparatorOrientation = 'horizontal' | 'vertical';

export interface BoSeparatorProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * The orientation of the separator.
	 * @default 'horizontal'
	 */
	orientation?: BoSeparatorOrientation;
	/**
	 * Whether the separator is purely decorative. Decorative separators
	 * are hidden from assistive technology.
	 * @default true
	 */
	decorative?: boolean;
	/** Optional visible label rendered at the center of the separator. */
	label?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoSeparatorManifestDefaults = Pick<BoSeparatorProps, 'orientation' | 'decorative' | 'role'>;

export interface BoSeparatorStyleManifest {
	base: string;
	orientation: Record<BoSeparatorOrientation, string>;
	withLabel: string;
	label: string;
}

export type SeparatorManifest = ComponentManifest<
	BoSeparatorStyleManifest,
	BoSeparatorManifestDefaults
>;
