import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoSidebarVariant = 'floating' | 'solid' | 'minimal';

export type BoSidebarPosition = 'static' | 'sticky' | 'fixed';

export type BoSidebarSide = 'left' | 'right';

export type BoSidebarWidth = 'narrow' | 'base' | 'wide';

export type BoSidebarCollapsedWidth = 'icon' | 'compact';

export type BoSidebarPadding = 'none' | 'sm' | 'md';

export type BoSidebarOffset = 'none' | 'sm' | 'md' | 'lg';

export type BoSidebarMaxWidth = 'none' | 'sm' | 'md' | 'lg' | 'xl';

export interface BoSidebarProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLAttributes['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** Visual treatment of the sidebar. @default 'floating' */
	variant?: BoSidebarVariant;
	/** Positioning strategy for the sidebar. @default 'sticky' */
	position?: BoSidebarPosition;
	/** Which side of the viewport the sidebar should stick to. @default 'left' */
	side?: BoSidebarSide;
	/** Expanded width preset. @default 'base' */
	width?: BoSidebarWidth;
	/** Collapsed width preset. @default 'icon' */
	collapsedWidth?: BoSidebarCollapsedWidth;
	/** Whether the sidebar is collapsed. @default false */
	collapsed?: boolean;
	/** Whether rounded corners are applied. @default true */
	rounded?: boolean;
	/** Whether elevation (shadow) is applied. @default true */
	shadow?: boolean;
	/** Whether borders are applied. @default true */
	border?: boolean;
	/** Padding preset for the sidebar content. @default 'md' */
	padding?: BoSidebarPadding;
	/** Top offset when using sticky or fixed positioning. @default 'md' */
	offset?: BoSidebarOffset;
	/** Max width constraint applied to the sidebar panel. @default 'none' */
	maxWidth?: BoSidebarMaxWidth;
	/** Enables vertical scrolling within the content area. @default true */
	scrollable?: boolean;
	/** The role of the sidebar element. @default 'complementary' */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

type BoSidebarManifestDefaults = Required<
	Pick<
		BoSidebarProps,
		| 'variant'
		| 'position'
		| 'side'
		| 'width'
		| 'collapsedWidth'
		| 'collapsed'
		| 'padding'
		| 'offset'
		| 'maxWidth'
		| 'rounded'
		| 'shadow'
		| 'border'
		| 'scrollable'
		| 'role'
	>
>;

type BoSidebarVariantStyleMap = Record<BoSidebarVariant, string>;
type BoSidebarPositionStyleMap = Record<BoSidebarPosition, string>;
type BoSidebarSideStyleMap = Record<BoSidebarSide, string>;
type BoSidebarWidthStyleMap = Record<BoSidebarWidth, string>;
type BoSidebarCollapsedWidthStyleMap = Record<BoSidebarCollapsedWidth, string>;
type BoSidebarPaddingStyleMap = Record<BoSidebarPadding, string>;
type BoSidebarOffsetStyleMap = Record<BoSidebarOffset, string>;
type BoSidebarMaxWidthStyleMap = Record<BoSidebarMaxWidth, string>;

export interface BoSidebarStyleManifest {
	outer: string;
	panel: string;
	text: string;
	header: string;
	content: string;
	footer: string;
	variant: BoSidebarVariantStyleMap;
	position: BoSidebarPositionStyleMap;
	side: BoSidebarSideStyleMap;
	width: BoSidebarWidthStyleMap;
	collapsedWidth: BoSidebarCollapsedWidthStyleMap;
	maxWidth: BoSidebarMaxWidthStyleMap;
	padding: BoSidebarPaddingStyleMap;
	offset: BoSidebarOffsetStyleMap;
	rounded: string;
	shadow: string;
	border: string;
	scrollable: string;
}

export type SidebarManifest = ComponentManifest<BoSidebarStyleManifest, BoSidebarManifestDefaults>;
