import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoTableSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoTableVariant = 'default' | 'striped' | 'bordered';

export interface BoTableColumn {
	/** Unique key for the column */
	key: string;
	/** Display label for the column header */
	label: string;
	/** Whether the column is sortable */
	sortable?: boolean;
	/** Width of the column (CSS value) */
	width?: string;
	/** Alignment of the column content */
	align?: 'left' | 'center' | 'right';
	/** Whether the column is sticky */
	sticky?: boolean;
}

export interface BoTableRow {
	/** Unique identifier for the row */
	id: string | number;
	/** Row data as key-value pairs */
	[key: string]: any;
}

export interface BoTableSort {
	/** Column key to sort by */
	key: string;
	/** Sort direction */
	direction: 'asc' | 'desc';
}

export interface BoTableProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the table.
	 * @default 'default'
	 */
	size?: BoTableSize;
	/**
	 * The variant of the table.
	 * @default 'default'
	 */
	variant?: BoTableVariant;
	/**
	 * Array of column definitions.
	 */
	columns: BoTableColumn[];
	/**
	 * Array of row data.
	 */
	rows: BoTableRow[];
	/**
	 * Current sort configuration.
	 */
	sort?: BoTableSort;
	/**
	 * Whether the table has a sticky header.
	 * @default false
	 */
	stickyHeader?: boolean;
	/**
	 * Whether rows are hoverable.
	 * @default true
	 */
	hoverable?: boolean;
	/**
	 * Whether rows are selectable.
	 * @default false
	 */
	selectable?: boolean;
	/**
	 * Array of selected row IDs.
	 */
	selectedRows?: (string | number)[];
	/**
	 * Loading state of the table.
	 * @default false
	 */
	loading?: boolean;
	/**
	 * Empty state message.
	 */
	emptyMessage?: string;
	/**
	 * Caption for the table.
	 */
	caption?: string;
}

export interface TableManifest extends ComponentManifest<
	{
		base: string;
		table: {
			base: string;
			size: Record<BoTableSize, string>;
			variant: Record<BoTableVariant, string>;
		};
		caption: string;
		header: {
			base: string;
			sticky: string;
		};
		headerRow: string;
		headerCell: {
			base: string;
			sortable: string;
			sorted: string;
			align: Record<'left' | 'center' | 'right', string>;
		};
		sortIcon: string;
		body: string;
		row: {
			base: string;
			hoverable: string;
			selectable: string;
			selected: string;
		};
		cell: {
			base: string;
			align: Record<'left' | 'center' | 'right', string>;
		};
		checkbox: string;
		loading: string;
		empty: string;
	},
	{
		size: BoTableSize;
		variant: BoTableVariant;
		stickyHeader: boolean;
		hoverable: boolean;
		selectable: boolean;
		loading: boolean;
		emptyMessage: string;
	}
> {}
