import { InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoToggleSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

export type BoToggleState = 'default' | 'valid' | 'invalid';

export interface BoToggleProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the toggle.
	 * @default 'default'
	 */
	size?: BoToggleSize;
	/**
	 * The state of the toggle.
	 * @default 'default'
	 */
	state?: BoToggleState;
	/**
	 * Whether the toggle is checked/enabled.
	 * @default false
	 */
	checked?: boolean;
	/**
	 * The label of the toggle.
	 */
	label?: string;
	/**
	 * Description for the toggle.
	 */
	description?: string;
	/**
	 * Error message to display when in invalid state.
	 */
	error?: string;
	/**
	 * Whether the toggle is required.
	 */
	required?: boolean;
	/**
	 * The name of the toggle.
	 */
	name?: HTMLInputElement['name'];
	/**
	 * Whether the toggle is disabled.
	 */
	disabled?: HTMLInputElement['disabled'];
	/**
	 * The value of the toggle.
	 */
	value?: string | number | boolean;
}

export interface ToggleManifest extends ComponentManifest<
	{
		base: string;
		container: string;
		track: {
			base: string;
			size: Record<BoToggleSize, string>;
			state: Record<BoToggleState, string>;
			disabled: string;
		};
		thumb: {
			base: string;
			size: Record<BoToggleSize, string>;
		};
		labelContainer: string;
		label: {
			base: string;
			size: Record<BoToggleSize, string>;
			disabled: string;
		};
		description: {
			base: string;
			size: Record<BoToggleSize, string>;
		};
		error: {
			base: string;
			size: Record<BoToggleSize, string>;
		};
	},
	{
		size: BoToggleSize;
		state: BoToggleState;
		checked: boolean;
	}
> {}
