import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoTimelineOrientation = 'vertical' | 'horizontal';

export type BoTimelineSize = 'sm' | 'default' | 'lg';

export interface BoTimelineProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The orientation of the timeline.
	 * @default 'vertical'
	 */
	orientation?: BoTimelineOrientation;
	/**
	 * The size of the timeline.
	 * @default 'default'
	 */
	size?: BoTimelineSize;
	/**
	 * The role of the timeline element.
	 * @default 'list'
	 */
	role?: HTMLAttributes['role'];
}

export interface BoTimelineItemProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The title of the timeline item.
	 */
	title?: string;
	/**
	 * The description of the timeline item.
	 */
	description?: string;
	/**
	 * The time/date of the timeline item.
	 */
	time?: string;
	/**
	 * The icon to display in the timeline marker.
	 */
	icon?: Icon;
	/**
	 * Whether this timeline item is active/current.
	 */
	active?: boolean;
	/**
	 * Whether this timeline item is completed.
	 */
	completed?: boolean;
	/**
	 * Custom color for the timeline marker.
	 */
	color?: string;
	/**
	 * The role of the timeline item element.
	 * @default 'listitem'
	 */
	role?: HTMLAttributes['role'];
}

type BoTimelineManifestDefaults = Pick<BoTimelineProps, 'orientation' | 'size' | 'role'>;
type BoTimelineItemManifestDefaults = Pick<BoTimelineItemProps, 'role'>;

type BoTimelineOrientationStyleMap = Record<BoTimelineOrientation, string>;
type BoTimelineSizeStyleMap = Record<BoTimelineSize, string>;

export interface BoTimelineStyleManifest {
	base: string;
	orientation: BoTimelineOrientationStyleMap;
	item: {
		base: string;
		orientation: BoTimelineOrientationStyleMap;
		marker: {
			base: string;
			size: BoTimelineSizeStyleMap;
			active: string;
			completed: string;
		};
		connector: {
			base: string;
			orientation: BoTimelineOrientationStyleMap;
		};
		content: {
			base: string;
			orientation: BoTimelineOrientationStyleMap;
		};
		title: string;
		description: string;
		time: string;
	};
}

export type TimelineManifest = ComponentManifest<
	BoTimelineStyleManifest,
	BoTimelineManifestDefaults
>;
export type TimelineItemManifest = ComponentManifest<
	BoTimelineStyleManifest,
	BoTimelineItemManifestDefaults
>;
