import { HTMLAttributes } from 'vue';
import { BoFontSize, BoIconSize, Icon } from './index.js';
import { ComponentManifest } from '../manifests/types.js';

export type BoTextareaSize = 'sm' | 'default' | 'lg';

export type BoTextareaState = 'default' | 'valid' | 'invalid';

export type BoTextareaVariant = 'default' | 'filled';

export interface BoTextareaProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLTextAreaElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * The size of the textarea.
	 * @default 'default'
	 */
	size?: BoTextareaSize;
	/**
	 * The state of the textarea.
	 * @default 'default'
	 */
	state?: BoTextareaState;
	/**
	 * The variant of the textarea.
	 * @default 'default'
	 */
	variant?: BoTextareaVariant;
	/** The placeholder text. */
	placeholder?: HTMLTextAreaElement['placeholder'];
	/** The label of the textarea. */
	label?: string;
	/** Description displayed below the textarea. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** Hint message to display below the textarea. */
	hint?: string;
	/** Whether the textarea is required. */
	required?: boolean;
	/** The name of the textarea. */
	name?: HTMLTextAreaElement['name'];
	/** Whether the textarea is disabled. */
	disabled?: HTMLTextAreaElement['disabled'];
	/** Whether the textarea is read-only. */
	readOnly?: HTMLTextAreaElement['readOnly'];
	/** Whether the textarea is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render. */
	prefixIcon?: Icon;
	/** The suffix icon to render. */
	suffixIcon?: Icon;
	/** Number of rows for the textarea. */
	rows?: HTMLTextAreaElement['rows'];
	/** Whether the textarea should be resizable. */
	resizable?: boolean;
	/** Maximum length of the textarea. */
	maxLength?: HTMLTextAreaElement['maxLength'];
	/** Whether the textarea should autofocus. */
	autofocus?: HTMLTextAreaElement['autofocus'];
	/** Whether the textarea should expand to fill available space. */
	expand?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}

type BoTextareaManifestDefaults = Pick<
	BoTextareaProps,
	| 'size'
	| 'state'
	| 'variant'
	| 'rows'
	| 'disabled'
	| 'readOnly'
	| 'required'
	| 'autofocus'
	| 'expand'
	| 'maxLength'
	| 'resizable'
>;

type BoTextareaSizeStyleMap = Record<BoTextareaSize, string>;
type BoTextareaStateStyleMap = Record<BoTextareaState, string>;
type BoTextareaVariantStyleMap = Record<BoTextareaVariant, string>;

interface BoTextareaStyleManifest {
	base: string;
	container: {
		base: string;
		disabled: string;
		expand: string;
	};
	textarea: {
		base: string;
		withPrefixIcon: string;
		withSuffixIcon: string;
		expand: string;
		resizable: string;
	};
	padding: BoTextareaSizeStyleMap;
	state: BoTextareaStateStyleMap;
	variant: BoTextareaVariantStyleMap;
	icons: {
		prefix: BoTextareaSizeStyleMap;
		suffix: BoTextareaSizeStyleMap;
		size: Record<BoTextareaSize, BoIconSize>;
	};
	labels: {
		container: string;
		required: string;
		fontSize: BoFontSize;
	};
	helpers: {
		error: string;
		hint: string;
		fontSize: BoFontSize;
	};
}

export type TextareaManifest = ComponentManifest<
	BoTextareaStyleManifest,
	BoTextareaManifestDefaults
>;
