import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export interface BoTagsInputProps {
	/** The id of the control. Autogenerated if not provided. */
	id?: HTMLInputElement['id'];
	/** The data test id of the control. Autogenerated if not provided. */
	dataTestId?: string;
	/** Placeholder text shown when no tag is being entered. */
	placeholder?: HTMLInputElement['placeholder'];
	/** Characters that commit the current input as a tag. */
	delimiters?: string[];
	/** Maximum number of tags allowed. */
	maxTags?: number;
	/** Whether duplicate tags should be accepted. */
	allowDuplicates?: boolean;
	/** Input keyboard hint. */
	inputMode?: InputHTMLAttributes['inputmode'];
	/** The form name of the control. */
	name?: HTMLInputElement['name'];
	/** The visible label. */
	label?: string;
	/** Description displayed below the control. */
	description?: string;
	/** Error message displayed below the control. */
	error?: string;
	/** Hint displayed below the control. */
	hint?: string;
	/** Whether the control is required. */
	required?: boolean;
	/** Whether the control is disabled. */
	disabled?: boolean;
	/** Whether the control is read-only. */
	readOnly?: boolean;
	/** Whether the input should receive focus on mount. */
	autofocus?: boolean;
	/** The role of the control. */
	role?: HTMLAttributes['role'];
	/** Accessible name for the control. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Accessible label reference for the control. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Accessible description reference for the control. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
}

export interface BoTagsInputStyleManifest {
	base: string;
	labels: { container: string; label: string; required: string };
	container: string;
	tags: string;
	tag: string;
	remove: string;
	input: string;
	helpers: { container: string; description: string; error: string; hint: string };
}

export type TagsInputManifest = ComponentManifest<BoTagsInputStyleManifest, Record<string, never>>;
