import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export type BoTooltipPlacement =
	| 'top'
	| 'top-start'
	| 'top-end'
	| 'bottom'
	| 'bottom-start'
	| 'bottom-end'
	| 'left'
	| 'left-start'
	| 'left-end'
	| 'right'
	| 'right-start'
	| 'right-end';

export type BoTooltipTrigger = 'hover' | 'focus' | 'click' | 'manual';

export interface BoTooltipProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The content to display in the tooltip.
	 */
	content?: string;
	/**
	 * The placement of the tooltip relative to the trigger element.
	 * @default 'top'
	 */
	placement?: BoTooltipPlacement;
	/**
	 * How the tooltip is triggered.
	 * @default 'hover'
	 */
	trigger?: BoTooltipTrigger;
	/**
	 * Whether the tooltip is disabled.
	 */
	disabled?: boolean;
	/**
	 * Whether the tooltip is visible (for manual trigger).
	 */
	visible?: boolean;
	/**
	 * Delay in milliseconds before showing the tooltip.
	 * @default 100
	 */
	showDelay?: number;
	/**
	 * Delay in milliseconds before hiding the tooltip.
	 * @default 100
	 */
	hideDelay?: number;
	/**
	 * The offset distance from the trigger element.
	 * @default 8
	 */
	offset?: number;
	/**
	 * Whether to show an arrow pointing to the trigger.
	 * @default true
	 */
	arrow?: boolean;
	/**
	 * The role of the tooltip element.
	 * @default 'tooltip'
	 */
	role?: HTMLAttributes['role'];
}

type BoTooltipManifestDefaults = Pick<
	BoTooltipProps,
	'placement' | 'trigger' | 'showDelay' | 'hideDelay' | 'offset' | 'arrow' | 'role'
>;

type BoTooltipPlacementStyleMap = Record<BoTooltipPlacement, string>;

export interface BoTooltipStyleManifest {
	base: string;
	arrow: string;
	placement: BoTooltipPlacementStyleMap;
	arrowPlacement: BoTooltipPlacementStyleMap;
}

export type TooltipManifest = ComponentManifest<BoTooltipStyleManifest, BoTooltipManifestDefaults>;
