import { HTMLAttributes } from 'vue';
import { ComponentManifest } from '../manifests/types.js';

export interface BoVisuallyHiddenProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
}

type BoVisuallyHiddenManifestDefaults = Record<string, never>;

export interface BoVisuallyHiddenStyleManifest {
	base: string;
}

export type VisuallyHiddenManifest = ComponentManifest<
	BoVisuallyHiddenStyleManifest,
	BoVisuallyHiddenManifestDefaults
>;
