import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon-registry';
import { BoLoaderType } from './bo-loader';

export type BoButtonVariant =
	| 'primary'
	| 'secondary'
	| 'success'
	| 'warning'
	| 'danger'
	| 'light'
	| 'dark';

export type BoButtonSize = 'xs' | 'sm' | 'default' | 'lg' | 'xl';

/**
 * - default: A filled button with a background color.
 * - pill: A filled button with fully rounded corners.
 * - outline: A button with a border and no background color.
 * - link: A button styled as a link with no background color or border.
 */
export type BoButtonShape = 'default' | 'pill' | 'outline' | 'link';

export interface BoButtonProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLButtonElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the button.
	 * @default 'md'
	 */
	size?: BoButtonSize;
	/**
	 * The variant of the button. This determines
	 * the color properties of the button.
	 *
	 * @default 'primary'
	 */
	variant?: BoButtonVariant;
	/**
	 * Whether the button is disabled. If so
	 * user interactions won't register.
	 */
	disabled?: boolean;
	/**
	 * Whether the button is loading. If so
	 * the button will display a loader before
	 * the label.
	 */
	isLoading?: boolean;
	/**
	 * Determines the type of loader to display when the button is loading.
	 * @default 'spinner'
	 */
	loaderType?: BoLoaderType;
	/**
	 * This determines the visual appearance
	 * of the element.
	 *
	 * - default: A filled button with a background color.
	 * - pill: A filled button with fully rounded corners.
	 * - outline: A button with a border and no background color.
	 * - link: A button styled as a link with no background color or border.
	 *
	 * @default 'default'
	 */
	shape?: BoButtonShape;
	/**
	 * Whether the button is pressed (for toggle buttons).
	 */
	pressed?: boolean;
	/**
	 * The type of the button.
	 * @default button
	 */
	type?: HTMLButtonElement['type'];
	/** The text content of the button. */
	label?: string;
	/** Whether the button is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Custom color for the button background (CSS variable, hex, rgb, rgba). */
	customColor?: {
		background?: string;
		border?: string;
		text?: string;
	};
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: HTMLAttributes['aria-labelledby'];
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: HTMLAttributes['aria-describedby'];
	/** Indicates that an element will be updated, and describes the types of updates the user agents,
	 * assistive technologies, and user can expect from the live region.
	 *
	 * - off: The element is not exposed to an assistive technology.
	 * - polite: The element is exposed to an assistive technology that "actively" indicates that user input will occur.
	 * - assertive: The element is exposed to an assistive technology that "passively" indicates that user input will occur.
	 *
	 * @default 'polite'
	 */
	ariaLive?: HTMLAttributes['aria-live'];
	/** Tab index of the element. */
	tabIndex?: HTMLAttributes['tabindex'];
}
