import { AriaLive } from '../core/bo-accessibility';
import { Icon } from './bo-icon';
import { BoLoaderType } from './bo-loader';

export type BoButtonVariant = 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'black';

export type BoButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

export type BoVariantStyle = Record<BoButtonVariant, string>;

export type BoButtonStyle = Record<BoButtonSize, string>;

/**
 * Tailwind CSS definitions for the different button variants. It defines
 * the background and text colors for the different button variants.
 */
export const BoButtonVariantStyle = {
	primary: /*tw*/ 'bg-blue-500 text-white dark:bg-blue-400 dark:text-white',
	secondary: /*tw*/ 'bg-neutral-500 text-white dark:bg-neutral-400 dark:text-white',
	success: /*tw*/ 'bg-green-500 text-white dark:bg-green-400 dark:text-white',
	warning: /*tw*/ 'bg-yellow-500 text-white dark:bg-yellow-400 dark:text-white',
	danger: /*tw*/ 'bg-red-500 text-white dark:bg-red-400 dark:text-white',
	black: /*tw*/ 'bg-black text-white dark:bg-black dark:text-white',
} as const satisfies BoVariantStyle;

export const BoButtonStyle = {
	xs: /*tw*/ 'px-2 py-1 text-xs',
	sm: /*tw*/ 'px-2.5 py-1.5 text-sm',
	md: /*tw*/ 'px-3 py-2 text-sm',
	lg: /*tw*/ 'px-4 py-2 text-base',
	xl: /*tw*/ 'px-6 py-3 text-base',
} as const satisfies BoButtonStyle;

export enum BoButtonType {
	button = 'button',
	submit = 'submit',
	reset = 'reset',
}

export interface BoButtonProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: string;
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/** The size of the button. @default md */
	size?: BoButtonSize;
	/** The variant of the button. @default primary */
	variant?: BoButtonVariant;
	/** Whether the button is disabled. */
	disabled?: boolean;
	/** Loading state of the button */
	isLoading?: boolean;
	/** The type of the loader @default spinner */
	loaderType?: BoLoaderType;
	/** The type of the button. */
	type?: BoButtonType;
	/** The text content of the button. */
	label?: string;
	/** Whether the button is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Custom color for the button background (CSS variable, hex, rgb, rgba). */
	customColor?: string;
	/** One or multiple css classes to be used for overriding the default styles on the element. */
	customCssClass?: string;
	/** The role of the element. */
	role?: string;
	/** Defines a string value that labels the current element. */
	ariaLabel?: string;
	/** Reference to an element that labels the current element. */
	ariaLabelledBy?: string;
	/** Identifies the element (or elements) that describes the object. */
	ariaDescribedBy?: string;
	/** Indicates that an element will be updated, and describes the types of updates the user agents,
	 * assistive technologies, and user can expect from the live region.
	 *
	 * - off: The element is not exposed to an assistive technology.
	 * - polite: The element is exposed to an assistive technology that "actively" indicates that user input will occur.
	 * - assertive: The element is exposed to an assistive technology that "passively" indicates that user input will occur.
	 */
	ariaLive?: AriaLive;
	/** Tab index of the element. */
	tabIndex?: number;
}
