import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { Icon } from './bo-icon-registry';

export type BoInputSize = 'sm' | 'md' | 'lg';

export type BoInputType = InputHTMLAttributes['type'];

export type BoInputState = 'default' | 'valid' | 'invalid';

export type BoInputVariant = 'default' | 'filled';

export type BoInputSizeStyleMap = Record<BoInputSize, string>;

export type BoInputVariantStyleMap = Record<BoInputState, string>;

export interface BoInputPill {
	/** Unique identifier for the pill */
	id: string;
	/** Text to display on the pill */
	text: string;
	/** Optional icon to display before pill text */
	icon?: Icon;
}

export interface BoInputProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: HTMLInputElement['id'];
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the input.
	 * @default 'md'
	 */
	size?: BoInputSize;
	/**
	 * The state of the input.
	 * @default 'default'
	 */
	state?: BoInputState;
	/**
	 * The variant of the input.
	 * @default 'default'
	 */
	variant?: BoInputVariant;
	/**
	 * The type of the input.
	 * @default 'text'
	 */
	type?: BoInputType;
	/** The placeholder of the input. */
	placeholder?: HTMLInputElement['placeholder'];
	/** The label of the input. */
	label?: string;
	/** Description for the input. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** The name of the input. */
	name?: HTMLInputElement['name'];
	/** Whether the input is disabled. */
	disabled?: HTMLInputElement['disabled'];
	/** Whether the input is read-only. */
	readOnly?: HTMLInputElement['readOnly'];
	/** Whether the input is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** Whether the input should autofocus */
	autofocus?: HTMLInputElement['autofocus'];
	/** Array of pill items to display in the input */
	pills?: BoInputPill[];
	/** Whether to enable horizontal scrolling for pills */
	horizontalScroll?: boolean;
	/** Whether to show toggle button for password input */
	revealPassword?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}
