import { HTMLAttributes } from 'vue';
import { type Icon } from './bo-icon-registry.js';
import { BoCursor } from '../core/cursor.js';

export type BoIconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;

export type BoIconSizeStyleMap = Record<BoIconSize, string>;

export type BoIconVariant =
	/** currentColor */
	| 'default'
	/** blue-500 | dark:blue-400 */
	| 'primary'
	/** neutral-500 | dark:neutral-400 */
	| 'secondary'
	/** green-500 | dark:green-400 */
	| 'success'
	/** orange-500 | dark:orange-400 */
	| 'warning'
	/** red-500 | dark:red-400 */
	| 'danger'
	/** white */
	| 'white'
	/** black */
	| 'black'
	/** currentColor */
	| 'current'
	/** inherit */
	| 'inherit';

export interface BoIconProps {
	/**
	 * The unique ID for the icon. Autogenerated
	 * if not provided.
	 */
	id?: string;
	/**
	 * The data-test-id of the icon. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The icon to display as a string from the
	 * `Icon` string literal type.
	 *
	 * @required
	 */
	icon: Icon;
	/**
	 * The size of the icon
	 * @default 'md'
	 */
	size?: BoIconSize;
	/**
	 * The color of the icon defined by the enum BoIconColor
	 * @default 'current'
	 */
	variant?: BoIconVariant;
	/** The color of the icon */
	customColor?: string;
	/** Custom css class passed to the root element */
	customCssClass?: string;
	/**
	 * Cursor type of the element. This must be a valid tailwind
	 * cursor value.
	 *
	 * @default 'cursor-auto'
	 */
	cursor?: BoCursor;
	/** The accessible title of the icon. */
	title?: string;
	/**
	 * The accessibility role of the icon.
	 * @default 'img'
	 */
	role?: HTMLAttributes['role'];
	/**
	 * Whether the icon is decorative which means that the icon is not
	 * a part of the UI and is only used to convey information.
	 */
	decorative?: boolean;
}
