import { HTMLAttributes, InputHTMLAttributes } from 'vue';
import { Icon } from './bo-icon-registry';

export type BoInputSize = 'sm' | 'md' | 'lg';

export type BoInputType = InputHTMLAttributes['type'];

export type BoInputState = 'default' | 'valid' | 'invalid';

export type BoInputSizeStyleMap = Record<BoInputSize, string>;

export type BoInputVariantStyleMap = Record<BoInputState, string>;

export interface BoInputProps {
	/**
	 * The id of the element. Autogenerated
	 * if not provided.
	 */
	id?: string;
	/**
	 * The data test id of the element. Autogenerated
	 * if not provided.
	 */
	dataTestId?: string;
	/**
	 * The size of the input.
	 * @default 'md'
	 */
	size?: BoInputSize;
	/**
	 * The state of the input.
	 * @default 'default'
	 */
	state?: BoInputState;
	/**
	 * The type of the input.
	 * @default 'text'
	 */
	type?: BoInputType;
	/** The placeholder of the input. */
	placeholder?: string;
	/** The label of the input. */
	label?: string;
	/** Hint text for the input. */
	hint?: string;
	/** The name of the input. */
	name?: string;
	/** Whether the input is disabled. */
	disabled?: boolean;
	/** Whether the input is read-only. */
	readOnly?: boolean;
	/** Whether the input is required. */
	required?: boolean;
	/** Whether the input is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render */
	prefixIcon?: Icon;
	/** The suffix icon to render */
	suffixIcon?: Icon;
	/** One or multiple css classes to be used for overriding the default styles on the element. */
	customCssClass?: string;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
}
