import { HTMLAttributes } from 'vue';
import { Icon } from './bo-icon-registry';

export type BoTextareaSize = 'sm' | 'md' | 'lg';

export type BoTextareaState = 'default' | 'valid' | 'invalid';

export type BoTextareaVariant = 'default' | 'filled';

export interface BoTextareaProps {
	/** The id of the element. Autogenerated if not provided. */
	id?: HTMLTextAreaElement['id'];
	/** The data test id of the element. Autogenerated if not provided. */
	dataTestId?: string;
	/**
	 * The size of the textarea.
	 * @default 'md'
	 */
	size?: BoTextareaSize;
	/**
	 * The state of the textarea.
	 * @default 'default'
	 */
	state?: BoTextareaState;
	/**
	 * The variant of the textarea.
	 * @default 'default'
	 */
	variant?: BoTextareaVariant;
	/** The placeholder text. */
	placeholder?: HTMLTextAreaElement['placeholder'];
	/** The label of the textarea. */
	label?: string;
	/** Description displayed below the textarea. */
	description?: string;
	/** Error message to display when in invalid state. */
	error?: string;
	/** The name of the textarea. */
	name?: HTMLTextAreaElement['name'];
	/** Whether the textarea is disabled. */
	disabled?: HTMLTextAreaElement['disabled'];
	/** Whether the textarea is read-only. */
	readOnly?: HTMLTextAreaElement['readOnly'];
	/** Whether the textarea is full width or not. */
	fullWidth?: boolean;
	/** The prefix icon to render. */
	prefixIcon?: Icon;
	/** The suffix icon to render. */
	suffixIcon?: Icon;
	/** Number of rows for the textarea. */
	rows?: HTMLTextAreaElement['rows'];
	/** Whether the textarea should be resizable. */
	resizable?: boolean;
	/** Maximum length of the textarea. */
	maxLength?: HTMLTextAreaElement['maxLength'];
	/** Whether the textarea should autofocus. */
	autofocus?: HTMLTextAreaElement['autofocus'];
	/** Whether the textarea should expand to fill available space. */
	expand?: boolean;
	/** The role of the element. */
	role?: HTMLAttributes['role'];
	/** Defines a string value that labels the current element. */
	ariaLabel?: HTMLAttributes['aria-label'];
}
