const TEXT_REPLACE_PLACEHOLDER = '__BLANK__';

const UNKNOWN_COLOR_WARNING = [
	`The custom color "__BLANK__" is not a valid color definition.`,
	'Valid color definitions are:',
	'\t- a named CSS color (e.g. red) see https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/named-color',
	'\t- a variable name (e.g. --my-color)',
	'\t- a hex color (e.g. #ff0000)',
	'\t- an rgb color (e.g. rgb(255, 0, 0))',
	'\t- an rgba color (e.g. rgba(255, 0, 0, 0.5))',
	'The custom color will be ignored an empty string will be returned instead.',
].join('\n');

/**
 * List of named CSS colors
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/named-color
 */
const NAMED_CSS_COLORS = new Set([
	'black',
	'silver',
	'gray',
	'white',
	'maroon',
	'red',
	'purple',
	'fuchsia',
	'green',
	'lime',
	'olive',
	'yellow',
	'navy',
	'blue',
	'teal',
	'aqua',
	'aliceblue',
	'antiquewhite',
	'aquamarine',
	'azure',
	'beige',
	'bisque',
	'blanchedalmond',
	'blueviolet',
	'brown',
	'burlywood',
	'cadetblue',
	'chartreuse',
	'chocolate',
	'coral',
	'cornflowerblue',
	'cornsilk',
	'crimson',
	'cyan',
	'darkblue',
	'darkcyan',
	'darkgoldenrod',
	'darkgray',
	'darkgreen',
	'darkgrey',
	'darkkhaki',
	'darkmagenta',
	'darkolivegreen',
	'darkorange',
	'darkorchid',
	'darkred',
	'darksalmon',
	'darkseagreen',
	'darkslateblue',
	'darkslategray',
	'darkslategrey',
	'darkturquoise',
	'darkviolet',
	'deeppink',
	'deepskyblue',
	'dimgray',
	'dimgrey',
	'dodgerblue',
	'firebrick',
	'floralwhite',
	'forestgreen',
	'gainsboro',
	'ghostwhite',
	'gold',
	'goldenrod',
	'greenyellow',
	'grey',
	'honeydew',
	'hotpink',
	'indianred',
	'indigo',
	'ivory',
	'khaki',
	'lavender',
	'lavenderblush',
	'lawngreen',
	'lemonchiffon',
	'lightblue',
	'lightcoral',
	'lightcyan',
	'lightgoldenrodyellow',
	'lightgray',
	'lightgreen',
	'lightgrey',
	'lightpink',
	'lightsalmon',
	'lightseagreen',
	'lightskyblue',
	'lightslategray',
	'lightslategrey',
	'lightsteelblue',
	'lightyellow',
	'limegreen',
	'linen',
	'magenta',
	'mediumaquamarine',
	'mediumblue',
	'mediumorchid',
	'mediumpurple',
	'mediumseagreen',
	'mediumslateblue',
	'mediumspringgreen',
	'mediumturquoise',
	'mediumvioletred',
	'midnightblue',
	'mintcream',
	'mistyrose',
	'moccasin',
	'navajowhite',
	'oldlace',
	'olivedrab',
	'orange',
	'orangered',
	'orchid',
	'palegoldenrod',
	'palegreen',
	'paleturquoise',
	'palevioletred',
	'papayawhip',
	'peachpuff',
	'peru',
	'pink',
	'plum',
	'powderblue',
	'rebeccapurple',
	'rosybrown',
	'royalblue',
	'saddlebrown',
	'salmon',
	'sandybrown',
	'seagreen',
	'seashell',
	'sienna',
	'skyblue',
	'slateblue',
	'slategray',
	'slategrey',
	'snow',
	'springgreen',
	'steelblue',
	'tan',
	'thistle',
	'tomato',
	'transparent',
	'turquoise',
	'violet',
	'wheat',
	'whitesmoke',
	'yellowgreen',
]);

export function getValidOrFallbackColorFromStr(prop: string): string {
	if (
		NAMED_CSS_COLORS.has(prop) ||
		prop.startsWith('#') ||
		prop.startsWith('oklch') ||
		prop.startsWith('rgb') ||
		prop.startsWith('rgba') ||
		prop.startsWith('var')
	) {
		return prop;
	} else if (prop.startsWith('--')) {
		/** CSS variable */
		return `var(${prop})`;
	} else if (prop?.length === 6) {
		/** Hex color without the leading # */
		return `#${prop}`;
	} else {
		console.warn(UNKNOWN_COLOR_WARNING.replace(TEXT_REPLACE_PLACEHOLDER, prop));
		return '';
	}
}
