import { ButtonManifest } from '../definitions/bo-button.js';

export const BUTTON_MANIFEST: ButtonManifest = {
	meta: {
		name: 'Button',
		version: '1.0.0',
	},
	styles: {
		base: 'bo-button',
		pressed: 'bo-button--pressed',
		shape: {
			default: 'bo-button--shape-default',
			pill: 'bo-button--shape-pill',
			flat: 'bo-button--shape-flat',
		},
		size: {
			xs: 'bo-button--xs',
			sm: 'bo-button--sm',
			default: 'bo-button--default',
			lg: 'bo-button--lg',
			xl: 'bo-button--xl',
		},
		iconOnlySize: {
			xs: 'bo-button--icon-only-xs',
			sm: 'bo-button--icon-only-sm',
			default: 'bo-button--icon-only-default',
			lg: 'bo-button--icon-only-lg',
			xl: 'bo-button--icon-only-xl',
		},
		variants: {
			default: {
				primary: 'bo-button--default-primary',
				secondary: 'bo-button--default-secondary',
				destructive: 'bo-button--default-destructive',
				warning: 'bo-button--default-warning',
				success: 'bo-button--default-success',
				light: 'bo-button--default-light',
				dark: 'bo-button--default-dark',
			},
			outline: {
				primary: 'bo-button--outline-primary',
				secondary: 'bo-button--outline-secondary',
				destructive: 'bo-button--outline-destructive',
				warning: 'bo-button--outline-warning',
				success: 'bo-button--outline-success',
				light: 'bo-button--outline-light',
				dark: 'bo-button--outline-dark',
			},
			ghost: {
				primary: 'bo-button--ghost-primary',
				secondary: 'bo-button--ghost-secondary',
				destructive: 'bo-button--ghost-destructive',
				warning: 'bo-button--ghost-warning',
				success: 'bo-button--ghost-success',
				light: 'bo-button--ghost-light',
				dark: 'bo-button--ghost-dark',
			},
			link: {
				primary: 'bo-button--link-primary',
				secondary: 'bo-button--link-secondary',
				destructive: 'bo-button--link-destructive',
				warning: 'bo-button--link-warning',
				success: 'bo-button--link-success',
				light: 'bo-button--link-light',
				dark: 'bo-button--link-dark',
			},
		},
		textColor: {
			default: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			outline: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			ghost: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			link: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
		},
		shadow: {
			default: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			outline: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			ghost: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
			link: {
				primary: '',
				secondary: '',
				destructive: '',
				warning: '',
				success: '',
				light: '',
				dark: '',
			},
		},
		fontSize: {
			xs: 'xs',
			sm: 'xs',
			default: 'sm',
			lg: 'sm',
			xl: 'lg',
		},
		iconSize: {
			xs: 'xs',
			sm: 'sm',
			default: 'sm',
			lg: 'sm',
			xl: 'default',
		},
		loaderSize: {
			xs: 'xs',
			sm: 'xs',
			default: 'sm',
			lg: 'default',
			xl: 'default',
		},
		cursor: {
			default: 'bo-button--cursor-default',
			disabled: 'bo-button--cursor-disabled',
			loading: 'bo-button--cursor-loading',
		},
		width: {
			default: '',
			full: 'bo-button--full-width',
		},
	},
	defaults: {
		type: 'button',
		role: 'button',
		kind: 'default',
		size: 'default',
		shape: 'default',
		variant: 'primary',
	},
};
