import { TooltipManifest } from '../definitions/bo-tooltip';

export const TOOLTIP_MANIFEST: TooltipManifest = {
	meta: {
		name: 'Tooltip',
		version: '1.0.0',
	},
	styles: {
		base: 'bo-tooltip',
		arrow: 'bo-tooltip__arrow',
		triggerWrapper: 'bo-tooltip__trigger',
		placement: {
			top: 'bo-tooltip--top',
			'top-start': 'bo-tooltip--top-start',
			'top-end': 'bo-tooltip--top-end',
			bottom: 'bo-tooltip--bottom',
			'bottom-start': 'bo-tooltip--bottom-start',
			'bottom-end': 'bo-tooltip--bottom-end',
			left: 'bo-tooltip--left',
			'left-start': 'bo-tooltip--left-start',
			'left-end': 'bo-tooltip--left-end',
			right: 'bo-tooltip--right',
			'right-start': 'bo-tooltip--right-start',
			'right-end': 'bo-tooltip--right-end',
		},
		arrowPlacement: {
			top: 'bo-tooltip__arrow--top',
			'top-start': 'bo-tooltip__arrow--top-start',
			'top-end': 'bo-tooltip__arrow--top-end',
			bottom: 'bo-tooltip__arrow--bottom',
			'bottom-start': 'bo-tooltip__arrow--bottom-start',
			'bottom-end': 'bo-tooltip__arrow--bottom-end',
			left: 'bo-tooltip__arrow--left',
			'left-start': 'bo-tooltip__arrow--left-start',
			'left-end': 'bo-tooltip__arrow--left-end',
			right: 'bo-tooltip__arrow--right',
			'right-start': 'bo-tooltip__arrow--right-start',
			'right-end': 'bo-tooltip__arrow--right-end',
		},
	},
	defaults: {
		placement: 'top',
		trigger: 'hover',
		showDelay: 100,
		hideDelay: 100,
		offset: 8,
		arrow: true,
		role: 'tooltip',
	},
};
