import { renderToString } from '@vue/server-renderer';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createSSRApp, h, nextTick } from 'vue';
import * as Bamboo from './index.js';

function renderTree() {
	return h('main', null, [
		h(Bamboo.BoButton, { id: 'hydration-button', dataTestId: 'hydration-button' }, () => 'Save'),
		h(
			Bamboo.BoTabs,
			{ id: 'hydration-tabs', dataTestId: 'hydration-tabs', defaultValue: 'one' },
			() => [
				h(Bamboo.BoTabsList, { id: 'hydration-tabs-list', dataTestId: 'hydration-tabs-list' }, () =>
					h(
						Bamboo.BoTabsTrigger,
						{ id: 'hydration-tabs-trigger', dataTestId: 'hydration-tabs-trigger', value: 'one' },
						() => 'One',
					),
				),
				h(
					Bamboo.BoTabsContent,
					{ id: 'hydration-tabs-content', dataTestId: 'hydration-tabs-content', value: 'one' },
					() => 'Content',
				),
			],
		),
	]);
}

describe('public components hydration', () => {
	afterEach(() => {
		vi.restoreAllMocks();
	});

	it('hydrates the server markup without mismatch warnings', async () => {
		const html = await renderToString(createSSRApp({ render: renderTree }));
		const container = document.createElement('div');
		container.innerHTML = html;
		document.body.append(container);
		const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);

		const app = createSSRApp({ render: renderTree });
		app.mount(container);
		await nextTick();

		expect(warn).not.toHaveBeenCalledWith(expect.stringContaining('Hydration node mismatch'));
		expect(container.querySelector('[data-testid="hydration-button"]')).not.toBeNull();
		expect(container.querySelector('[data-testid="hydration-tabs-content"]')).not.toBeNull();

		app.unmount();
		container.remove();
	});

	it('keeps autogenerated ids stable across SSR and hydration', async () => {
		const html = await renderToString(
			createSSRApp({ render: () => h(Bamboo.BoProgress, { value: 40 }) }),
		);
		const serverId = html.match(/id="([^"]+)"/)?.[1];
		const container = document.createElement('div');
		container.innerHTML = html;
		document.body.append(container);
		const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);

		const app = createSSRApp({ render: () => h(Bamboo.BoProgress, { value: 40 }) });
		app.mount(container);
		await nextTick();

		expect(serverId).toBeTruthy();
		expect(container.firstElementChild?.id).toBe(serverId);
		expect(warn).not.toHaveBeenCalledWith(expect.stringContaining('Hydration'));

		app.unmount();
		container.remove();
	});
});
