name: 'lint'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Type Check
        run: |
          pnpm type-check

      - name: Run Lint
        run: |
          pnpm lint

      - name: Run Spell Check
        run: |
          pnpm lint:spell
