name: 'lint'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup LTS Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run eslint
        run: |
          pnpm lint:eslint

  run-oxlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup LTS Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run oxlint
        run: |
          pnpm lint:oxlint
